Traceback (most recent call last):
  File "scripts/node2.py", line 22, in <module>
    main()
  File "scripts/node2.py", line 17, in main
    string = socket.recv()
NameError: global name 'socket' is not defined
Traceback (most recent call last):
  File "scripts/node2.py", line 27, in <module>
    main()
  File "scripts/node2.py", line 14, in main
    receiver.bind("tcp://localhost:9998")
  File "zmq/backend/cython/socket.pyx", line 487, in zmq.backend.cython.socket.Socket.bind (zmq/backend/cython/socket.c:5156)
  File "zmq/backend/cython/checkrc.pxd", line 25, in zmq.backend.cython.checkrc._check_rc (zmq/backend/cython/socket.c:7535)
zmq.error.ZMQError: No such device
Traceback (most recent call last):
  File "scripts/node2.py", line 27, in <module>
    main()
  File "scripts/node2.py", line 14, in main
    receiver.bind("tcp://localhost:9998")
  File "zmq/backend/cython/socket.pyx", line 487, in zmq.backend.cython.socket.Socket.bind (zmq/backend/cython/socket.c:5156)
  File "zmq/backend/cython/checkrc.pxd", line 25, in zmq.backend.cython.checkrc._check_rc (zmq/backend/cython/socket.c:7535)
zmq.error.ZMQError: No such device
Traceback (most recent call last):
  File "scripts/node2.py", line 27, in <module>
    main()
  File "scripts/node2.py", line 14, in main
    receiver.bind("tcp://localhost:9998")
  File "zmq/backend/cython/socket.pyx", line 487, in zmq.backend.cython.socket.Socket.bind (zmq/backend/cython/socket.c:5156)
  File "zmq/backend/cython/checkrc.pxd", line 25, in zmq.backend.cython.checkrc._check_rc (zmq/backend/cython/socket.c:7535)
zmq.error.ZMQError: No such device
Traceback (most recent call last):
  File "scripts/node2.py", line 27, in <module>
    main()
  File "scripts/node2.py", line 23, in main
    topic, messagedata = string.split()
ValueError: too many values to unpack
Traceback (most recent call last):
  File "scripts/node2.py", line 27, in <module>
    main()
  File "scripts/node2.py", line 23, in main
    topic, messagedata = string.split()
ValueError: too many values to unpack
Traceback (most recent call last):
  File "scripts/node2.py", line 27, in <module>
    main()
  File "scripts/node2.py", line 23, in main
    topic, messagedata = string.split()
ValueError: too many values to unpack
Traceback (most recent call last):
  File "scripts/node2.py", line 27, in <module>
    main()
  File "scripts/node2.py", line 23, in main
    topic, messagedata = string.split()
ValueError: too many values to unpack
Traceback (most recent call last):
  File "scripts/node2.py", line 27, in <module>
    main()
  File "scripts/node2.py", line 23, in main
    topic, messagedata = string.split()
ValueError: too many values to unpack
Traceback (most recent call last):
  File "scripts/node2.py", line 27, in <module>
    main()
  File "scripts/node2.py", line 23, in main
    topic, messagedata = string.split()
ValueError: too many values to unpack
Traceback (most recent call last):
  File "scripts/node2.py", line 27, in <module>
    main()
  File "scripts/node2.py", line 23, in main
    topic, messagedata = string.split()
ValueError: too many values to unpack
Traceback (most recent call last):
  File "scripts/node2.py", line 27, in <module>
    main()
  File "scripts/node2.py", line 23, in main
    topic, messagedata = string.split()
ValueError: too many values to unpack
Traceback (most recent call last):
  File "scripts/node2.py", line 27, in <module>
    main()
  File "scripts/node2.py", line 23, in main
    topic, messagedata = string.split()
ValueError: too many values to unpack
Traceback (most recent call last):
  File "scripts/node2.py", line 27, in <module>
    main()
  File "scripts/node2.py", line 23, in main
    topic, messagedata = string.split()
ValueError: too many values to unpack
Traceback (most recent call last):
  File "scripts/node2.py", line 27, in <module>
    main()
  File "scripts/node2.py", line 23, in main
    topic, messagedata = string.split()
ValueError: too many values to unpack
Traceback (most recent call last):
  File "scripts/node2.py", line 27, in <module>
    main()
  File "scripts/node2.py", line 23, in main
    topic, messagedata = string.split()
ValueError: too many values to unpack
Traceback (most recent call last):
  File "scripts/node2.py", line 27, in <module>
    main()
  File "scripts/node2.py", line 23, in main
    topic, messagedata = string.split()
ValueError: too many values to unpack
Traceback (most recent call last):
  File "scripts/node2.py", line 27, in <module>
    main()
  File "scripts/node2.py", line 23, in main
    topic, messagedata = string.split()
ValueError: too many values to unpack
python: can't open file 'scripts/thread.py': [Errno 2] No such file or directory
  File "scripts/threads.py", line 17
    print_out "%s: %s" % ( threadName, time.ctime(time.time()) )
                     ^
SyntaxError: invalid syntax
  File "scripts/threads.py", line 17
    print_out "%s: %s" % ( threadName, time.ctime(time.time()) )
                     ^
SyntaxError: invalid syntax
  File "scripts/threads.py", line 17
    print_out "%s: %s" % ( threadName, time.ctime(time.time()) )
                     ^
SyntaxError: invalid syntax
  File "scripts/threads.py", line 17
    print_out "%s: %s" % ( threadName, time.ctime(time.time()) )
                     ^
SyntaxError: invalid syntax
  File "scripts/threads.py", line 17
    print_out "%s: %s" % ( threadName, time.ctime(time.time()) )
                     ^
SyntaxError: invalid syntax
  File "scripts/threads.py", line 20
    try:
      ^
SyntaxError: invalid syntax
  File "scripts/threads.py", line 20
    try:
      ^
SyntaxError: invalid syntax
  File "scripts/threads.py", line 20
    try:
      ^
SyntaxError: invalid syntax
Unhandled exception in thread started by <function print_time at 0x7f8826c75848>
Traceback (most recent call last):
  File "scripts/threads.py", line 17, in print_time
    print_out (threadName)
  File "scripts/threads.py", line 7, in print_out
    sys.stdout.write( str )
NameError: global name 'sys' is not defined
Unhandled exception in thread started by <function print_time at 0x7f8826c75848>
Traceback (most recent call last):
  File "scripts/threads.py", line 17, in print_time
    print_out (threadName)
  File "scripts/threads.py", line 7, in print_out
    sys.stdout.write( str )
NameError: global name 'sys' is not defined
Unhandled exception in thread started by <function print_time at 0x7f1f6a451aa0>
TypeErrorUnhandled exception in thread started by <function print_time at 0x7f1f6a451aa0>
TypeError: : print_time() takes exactly 1 argument (2 given)
print_time() takes exactly 1 argument (2 given)
Traceback (most recent call last):
  File "scripts/node2.py", line 32, in <module>
    main()
  File "scripts/node2.py", line 17, in main
    receiver.bind("tcp://127.0.0.1:9999")
  File "zmq/backend/cython/socket.pyx", line 487, in zmq.backend.cython.socket.Socket.bind (zmq/backend/cython/socket.c:5156)
  File "zmq/backend/cython/checkrc.pxd", line 25, in zmq.backend.cython.checkrc._check_rc (zmq/backend/cython/socket.c:7535)
zmq.error.ZMQError: Address already in use
Traceback (most recent call last):
  File "scripts/node2.py", line 32, in <module>
    main()
  File "scripts/node2.py", line 17, in main
    receiver.bind("tcp://127.0.0.1:9999")
  File "zmq/backend/cython/socket.pyx", line 487, in zmq.backend.cython.socket.Socket.bind (zmq/backend/cython/socket.c:5156)
  File "zmq/backend/cython/checkrc.pxd", line 25, in zmq.backend.cython.checkrc._check_rc (zmq/backend/cython/socket.c:7535)
zmq.error.ZMQError: Address already in use
Traceback (most recent call last):
  File "scripts/node2.py", line 32, in <module>
    main()
  File "scripts/node2.py", line 17, in main
    receiver.bind("tcp://127.0.0.1:9999")
  File "zmq/backend/cython/socket.pyx", line 487, in zmq.backend.cython.socket.Socket.bind (zmq/backend/cython/socket.c:5156)
  File "zmq/backend/cython/checkrc.pxd", line 25, in zmq.backend.cython.checkrc._check_rc (zmq/backend/cython/socket.c:7535)
zmq.error.ZMQError: Address already in use
Traceback (most recent call last):
  File "scripts/node2.py", line 32, in <module>
    main()
  File "scripts/node2.py", line 17, in main
    receiver.bind("tcp://127.0.0.1:9999")
  File "zmq/backend/cython/socket.pyx", line 487, in zmq.backend.cython.socket.Socket.bind (zmq/backend/cython/socket.c:5156)
  File "zmq/backend/cython/checkrc.pxd", line 25, in zmq.backend.cython.checkrc._check_rc (zmq/backend/cython/socket.c:7535)
zmq.error.ZMQError: Address already in use
Traceback (most recent call last):
  File "scripts/node2.py", line 32, in <module>
    main()
  File "scripts/node2.py", line 17, in main
    receiver.bind("tcp://127.0.0.1:9999")
  File "zmq/backend/cython/socket.pyx", line 487, in zmq.backend.cython.socket.Socket.bind (zmq/backend/cython/socket.c:5156)
  File "zmq/backend/cython/checkrc.pxd", line 25, in zmq.backend.cython.checkrc._check_rc (zmq/backend/cython/socket.c:7535)
zmq.error.ZMQError: Address already in use
Traceback (most recent call last):
  File "scripts/node2.py", line 32, in <module>
    main()
  File "scripts/node2.py", line 28, in main
    print_out("Node 2 recieved: " % string)
TypeError: not all arguments converted during string formatting
Traceback (most recent call last):
  File "scripts/node2.py", line 32, in <module>
    main()
  File "scripts/node2.py", line 28, in main
    print_out("Node 2 recieved: " % string)
TypeError: not all arguments converted during string formatting
Traceback (most recent call last):
  File "scripts/node2.py", line 32, in <module>
    main()
  File "scripts/node2.py", line 28, in main
    print_out("Node 2 recieved: " % string)
TypeError: not all arguments converted during string formatting
Traceback (most recent call last):
  File "scripts/node2.py", line 29, in <module>
    main()
  File "scripts/node2.py", line 15, in main
    receiver = can.init_reciever(id_filter)
  File "/home/nebu/supervisor/scripts/can.py", line 21, in init_reciever
    return reciever
NameError: global name 'reciever' is not defined
Traceback (most recent call last):
  File "scripts/node2.py", line 29, in <module>
    main()
  File "scripts/node2.py", line 15, in main
    receiver = can.init_reciever(id_filter)
  File "/home/nebu/supervisor/scripts/can.py", line 21, in init_reciever
    return reciever
NameError: global name 'reciever' is not defined
Traceback (most recent call last):
  File "scripts/node2.py", line 29, in <module>
    main()
  File "scripts/node2.py", line 15, in main
    receiver = can.init_reciever(id_filter)
  File "/home/nebu/supervisor/scripts/can.py", line 21, in init_reciever
    return reciever
NameError: global name 'reciever' is not defined
Traceback (most recent call last):
  File "scripts/node2.py", line 29, in <module>
    main()
  File "scripts/node2.py", line 15, in main
    receiver = can.init_reciever(id_filter)
  File "/home/nebu/supervisor/scripts/can.py", line 21, in init_reciever
    return reciever
NameError: global name 'reciever' is not defined
Traceback (most recent call last):
  File "scripts/node2.py", line 29, in <module>
    main()
  File "scripts/node2.py", line 15, in main
    receiver = can.init_receiver(id_filter)
  File "/home/nebu/supervisor/scripts/can.py", line 21, in init_receiver
    return reciever
NameError: global name 'reciever' is not defined
Traceback (most recent call last):
  File "scripts/node2.py", line 29, in <module>
    main()
  File "scripts/node2.py", line 15, in main
    receiver = can.init_receiver(id_filter)
  File "/home/nebu/supervisor/scripts/can.py", line 21, in init_receiver
    return reciever
NameError: global name 'reciever' is not defined
Traceback (most recent call last):
  File "scripts/node2.py", line 29, in <module>
    main()
  File "scripts/node2.py", line 15, in main
    receiver = can.init_receiver(id_filter)
  File "/home/nebu/supervisor/scripts/can.py", line 21, in init_receiver
    return reciever
NameError: global name 'reciever' is not defined
Traceback (most recent call last):
  File "scripts/node2.py", line 29, in <module>
    main()
  File "scripts/node2.py", line 15, in main
    receiver = can.init_receiver(id_filter)
  File "/home/nebu/supervisor/scripts/can.py", line 21, in init_receiver
    return reciever
NameError: global name 'reciever' is not defined
Traceback (most recent call last):
  File "scripts/node2.py", line 32, in <module>
    main()
  File "scripts/node2.py", line 23, in main
    sender.send("%s %s" % message_id, message_data )
TypeError: not enough arguments for format string
Traceback (most recent call last):
  File "scripts/node2.py", line 32, in <module>
    main()
  File "scripts/node2.py", line 23, in main
    sender.send("%s %s" % message_id, message_data )
TypeError: not enough arguments for format string
Traceback (most recent call last):
  File "scripts/node2.py", line 32, in <module>
    main()
  File "scripts/node2.py", line 23, in main
    sender.send("%s %s" % message_id, message_data )
TypeError: not enough arguments for format string
Traceback (most recent call last):
  File "scripts/node2.py", line 32, in <module>
    main()
  File "scripts/node2.py", line 23, in main
    sender.send("%s %s" % message_id, message_data )
TypeError: not enough arguments for format string
Traceback (most recent call last):
  File "scripts/node2.py", line 32, in <module>
    main()
  File "scripts/node2.py", line 23, in main
    sender.send("%s %s" % message_id, message_data )
TypeError: not enough arguments for format string
Traceback (most recent call last):
  File "scripts/node2.py", line 32, in <module>
    main()
  File "scripts/node2.py", line 23, in main
    sender.send("%s %s" % message_id, message_data )
TypeError: not enough arguments for format string
Traceback (most recent call last):
  File "scripts/node2.py", line 32, in <module>
    main()
  File "scripts/node2.py", line 23, in main
    sender.send("%s %s" % message_id, message_data )
TypeError: not enough arguments for format string
Traceback (most recent call last):
  File "scripts/node2.py", line 32, in <module>
    main()
  File "scripts/node2.py", line 23, in main
    sender.send("%s %s" % message_id, message_data )
TypeError: not enough arguments for format string
Traceback (most recent call last):
  File "scripts/node2.py", line 32, in <module>
    main()
  File "scripts/node2.py", line 23, in main
    sender.send("%s %s" % message_id, message_data )
TypeError: not enough arguments for format string
Traceback (most recent call last):
  File "scripts/node2.py", line 32, in <module>
    main()
  File "scripts/node2.py", line 23, in main
    sender.send("%s %s" % message_id, message_data )
TypeError: not enough arguments for format string
Traceback (most recent call last):
  File "scripts/node2.py", line 32, in <module>
    main()
  File "scripts/node2.py", line 23, in main
    sender.send("%s %s" % message_id, message_data )
TypeError: not enough arguments for format string
Traceback (most recent call last):
  File "scripts/node2.py", line 32, in <module>
    main()
  File "scripts/node2.py", line 23, in main
    sender.send("%s %s" % message_id, message_data )
TypeError: not enough arguments for format string
Traceback (most recent call last):
  File "scripts/node2.py", line 32, in <module>
    main()
  File "scripts/node2.py", line 23, in main
    sender.send("%s %s" % message_id, message_data )
TypeError: not enough arguments for format string
Traceback (most recent call last):
  File "scripts/node2.py", line 32, in <module>
    main()
  File "scripts/node2.py", line 23, in main
    sender.send("%s %s" % message_id, message_data )
TypeError: not enough arguments for format string
Traceback (most recent call last):
  File "scripts/node2.py", line 32, in <module>
    main()
  File "scripts/node2.py", line 23, in main
    sender.send("%s %s" % message_id, message_data )
TypeError: not enough arguments for format string
Traceback (most recent call last):
  File "scripts/node2.py", line 32, in <module>
    main()
  File "scripts/node2.py", line 23, in main
    sender.send("%s %s" % message_id, message_data )
TypeError: not enough arguments for format string
Traceback (most recent call last):
  File "scripts/node2.py", line 32, in <module>
    main()
  File "scripts/node2.py", line 23, in main
    sender.send("%s %s" % message_id, message_data )
TypeError: not enough arguments for format string
Traceback (most recent call last):
  File "scripts/node2.py", line 32, in <module>
    main()
  File "scripts/node2.py", line 23, in main
    sender.send("%s %s" % message_id, message_data )
TypeError: not enough arguments for format string
Traceback (most recent call last):
  File "scripts/node2.py", line 32, in <module>
    main()
  File "scripts/node2.py", line 23, in main
    sender.send("%s %s" % message_id, message_data )
TypeError: not enough arguments for format string
Traceback (most recent call last):
  File "scripts/node2.py", line 32, in <module>
    main()
  File "scripts/node2.py", line 23, in main
    sender.send("%s %s" % message_id, message_data )
TypeError: not enough arguments for format string
Traceback (most recent call last):
  File "scripts/node2.py", line 32, in <module>
    main()
  File "scripts/node2.py", line 23, in main
    sender.send("%s %s" % message_id, message_data )
TypeError: not enough arguments for format string
Traceback (most recent call last):
  File "scripts/node2.py", line 32, in <module>
    main()
  File "scripts/node2.py", line 23, in main
    sender.send("%s %s" % message_id, message_data )
TypeError: not enough arguments for format string
Traceback (most recent call last):
  File "scripts/node2.py", line 32, in <module>
    main()
  File "scripts/node2.py", line 23, in main
    sender.send("%s %s" % message_id, message_data )
TypeError: not enough arguments for format string
Traceback (most recent call last):
  File "scripts/node2.py", line 32, in <module>
    main()
  File "scripts/node2.py", line 23, in main
    sender.send("%s %s" % message_id, message_data )
TypeError: not enough arguments for format string
Traceback (most recent call last):
  File "scripts/node2.py", line 32, in <module>
    main()
  File "scripts/node2.py", line 23, in main
    sender.send("%s %s" % message_id, message_data )
TypeError: not enough arguments for format string
Traceback (most recent call last):
  File "scripts/node2.py", line 32, in <module>
    main()
  File "scripts/node2.py", line 23, in main
    sender.send("%s %s" % message_id, message_data )
TypeError: not enough arguments for format string
Traceback (most recent call last):
  File "scripts/node2.py", line 32, in <module>
    main()
  File "scripts/node2.py", line 23, in main
    sender.send("%s %s" % message_id, message_data )
TypeError: not enough arguments for format string
Traceback (most recent call last):
  File "scripts/node2.py", line 32, in <module>
    main()
  File "scripts/node2.py", line 23, in main
    sender.send("%s %s" % message_id, message_data )
TypeError: not enough arguments for format string
Traceback (most recent call last):
  File "scripts/node2.py", line 32, in <module>
    main()
  File "scripts/node2.py", line 23, in main
    sender.send("%s %s" % message_id, message_data )
TypeError: not enough arguments for format string
Traceback (most recent call last):
  File "scripts/node2.py", line 32, in <module>
    main()
  File "scripts/node2.py", line 23, in main
    sender.send("%s %s" % message_id, message_data )
TypeError: not enough arguments for format string
Traceback (most recent call last):
  File "scripts/node2.py", line 32, in <module>
    main()
  File "scripts/node2.py", line 23, in main
    sender.send("%s %s" % message_id, message_data )
TypeError: not enough arguments for format string
Traceback (most recent call last):
  File "scripts/node2.py", line 32, in <module>
    main()
  File "scripts/node2.py", line 23, in main
    sender.send("%s %s" % message_id, message_data )
TypeError: not enough arguments for format string
Traceback (most recent call last):
  File "scripts/node2.py", line 32, in <module>
    main()
  File "scripts/node2.py", line 23, in main
    sender.send("%s %s" % message_id, message_data )
TypeError: not enough arguments for format string
Traceback (most recent call last):
  File "scripts/node2.py", line 32, in <module>
    main()
  File "scripts/node2.py", line 23, in main
    sender.send("%s %s" % message_id, message_data )
TypeError: not enough arguments for format string
Traceback (most recent call last):
  File "scripts/node2.py", line 32, in <module>
    main()
  File "scripts/node2.py", line 23, in main
    sender.send("%s %s" % message_id, message_data )
TypeError: not enough arguments for format string
Traceback (most recent call last):
  File "scripts/node2.py", line 32, in <module>
    main()
  File "scripts/node2.py", line 23, in main
    sender.send("%s %s" % message_id, message_data )
TypeError: not enough arguments for format string
Traceback (most recent call last):
  File "scripts/node2.py", line 32, in <module>
    main()
  File "scripts/node2.py", line 23, in main
    sender.send("%s %s" % message_id, message_data )
TypeError: not enough arguments for format string
Traceback (most recent call last):
  File "scripts/node2.py", line 32, in <module>
    main()
  File "scripts/node2.py", line 23, in main
    sender.send("%s %s" % message_id, message_data )
TypeError: not enough arguments for format string
Traceback (most recent call last):
  File "scripts/node2.py", line 32, in <module>
    main()
  File "scripts/node2.py", line 23, in main
    sender.send("%s %s" % message_id, message_data )
TypeError: not enough arguments for format string
  File "scripts/node2.py", line 23
    sender.send("%s %s" % message_id message_data )
                                                ^
SyntaxError: invalid syntax
  File "scripts/node2.py", line 23
    sender.send("%s %s" % message_id message_data )
                                                ^
SyntaxError: invalid syntax
  File "scripts/node2.py", line 23
    sender.send("%s %s" % message_id message_data )
                                                ^
SyntaxError: invalid syntax
  File "scripts/node2.py", line 23
    sender.send("%s %s" % message_id message_data )
                                                ^
SyntaxError: invalid syntax
  File "scripts/node2.py", line 23
    sender.send("%s %s" % message_id message_data )
                                                ^
SyntaxError: invalid syntax
  File "scripts/node2.py", line 23
    sender.send("%s %s" % message_id message_data )
                                                ^
SyntaxError: invalid syntax
  File "scripts/node2.py", line 23
    sender.send("%s %s" % message_id message_data )
                                                ^
SyntaxError: invalid syntax
  File "scripts/node2.py", line 23
    sender.send("%s %s" % message_id message_data )
                                                ^
SyntaxError: invalid syntax
  File "scripts/node2.py", line 23
    sender.send("%s %s" % message_id message_data )
                                                ^
SyntaxError: invalid syntax
  File "scripts/node2.py", line 23
    sender.send("%s %s" % message_id message_data )
                                                ^
SyntaxError: invalid syntax
  File "scripts/node2.py", line 23
    sender.send("%s %s" % message_id message_data )
                                                ^
SyntaxError: invalid syntax
  File "scripts/node2.py", line 23
    sender.send("%s %s" % message_id message_data )
                                                ^
SyntaxError: invalid syntax
  File "scripts/node2.py", line 23
    sender.send("%s %s" % message_id message_data )
                                                ^
SyntaxError: invalid syntax
  File "scripts/node2.py", line 23
    sender.send("%s %s" % message_id message_data )
                                                ^
SyntaxError: invalid syntax
  File "scripts/node2.py", line 23
    sender.send("%s %s" % message_id message_data )
                                                ^
SyntaxError: invalid syntax
  File "scripts/node2.py", line 23
    sender.send("%s %s" % message_id message_data )
                                                ^
SyntaxError: invalid syntax
  File "scripts/node2.py", line 23
    sender.send("%s %s" % message_id message_data )
                                                ^
SyntaxError: invalid syntax
  File "scripts/node2.py", line 23
    sender.send("%s %s" % message_id message_data )
                                                ^
SyntaxError: invalid syntax
  File "scripts/node2.py", line 23
    sender.send("%s %s" % message_id message_data )
                                                ^
SyntaxError: invalid syntax
  File "scripts/node2.py", line 23
    sender.send("%s %s" % message_id message_data )
                                                ^
SyntaxError: invalid syntax
  File "scripts/node2.py", line 23
    sender.send("%s %s" % message_id message_data )
                                                ^
SyntaxError: invalid syntax
  File "scripts/node2.py", line 23
    sender.send("%s %s" % message_id message_data )
                                                ^
SyntaxError: invalid syntax
  File "scripts/node2.py", line 23
    sender.send("%s %s" % message_id message_data )
                                                ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "scripts/node2.py", line 40, in <module>
    main()
  File "scripts/node2.py", line 17, in main
    receiver = can.init_receiver(id_filter)
  File "/home/nebu/supervisor/scripts/can.py", line 19, in init_receiver
    receiver.setsockopt(zmq.SUBSCRIBE, id_filter)
  File "zmq/backend/cython/socket.pyx", line 372, in zmq.backend.cython.socket.Socket.set (zmq/backend/cython/socket.c:4220)
TypeError: expected bytes, got: ['50', '70', '200']
Traceback (most recent call last):
  File "scripts/node2.py", line 40, in <module>
    main()
  File "scripts/node2.py", line 17, in main
    receiver = can.init_receiver(id_filter)
  File "/home/nebu/supervisor/scripts/can.py", line 19, in init_receiver
    receiver.setsockopt(zmq.SUBSCRIBE, id_filter)
  File "zmq/backend/cython/socket.pyx", line 372, in zmq.backend.cython.socket.Socket.set (zmq/backend/cython/socket.c:4220)
TypeError: expected bytes, got: ['50', '70', '200']
Traceback (most recent call last):
  File "scripts/node2.py", line 40, in <module>
    main()
  File "scripts/node2.py", line 17, in main
    receiver = can.init_receiver(id_filter)
  File "/home/nebu/supervisor/scripts/can.py", line 19, in init_receiver
    receiver.setsockopt(zmq.SUBSCRIBE, id_filter)
  File "zmq/backend/cython/socket.pyx", line 372, in zmq.backend.cython.socket.Socket.set (zmq/backend/cython/socket.c:4220)
TypeError: expected bytes, got: ['50', '70', '200']
Traceback (most recent call last):
  File "scripts/node2.py", line 4, in <module>
    import can
  File "/home/nebu/supervisor/scripts/can.py", line 3
    def set_id_filter(socket zmq.Socket, filters):
                               ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "scripts/node2.py", line 4, in <module>
    import can
  File "/home/nebu/supervisor/scripts/can.py", line 3
    def set_id_filter(socket zmq.Socket, filters):
                               ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "scripts/node2.py", line 4, in <module>
    import can
  File "/home/nebu/supervisor/scripts/can.py", line 3
    def set_id_filter(socket zmq.Socket, filters):
                               ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "scripts/node2.py", line 4, in <module>
    import can
  File "/home/nebu/supervisor/scripts/can.py", line 3
    def set_id_filter(socket zmq.Socket, filters):
                               ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "scripts/node2.py", line 4, in <module>
    import can
  File "/home/nebu/supervisor/scripts/can.py", line 3
    def set_id_filter(socket zmq.Socket, filters):
                               ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "scripts/node2.py", line 4, in <module>
    import can
  File "/home/nebu/supervisor/scripts/can.py", line 3
    def set_id_filter(socket zmq.Socket, filters):
                               ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "scripts/node2.py", line 4, in <module>
    import can
  File "/home/nebu/supervisor/scripts/can.py", line 3
    def set_id_filter(socket zmq.Socket, filters):
                               ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "scripts/node2.py", line 4, in <module>
    import can
  File "/home/nebu/supervisor/scripts/can.py", line 3
    def set_id_filter(socket zmq.Socket, filters):
                               ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "scripts/node2.py", line 4, in <module>
    import can
  File "/home/nebu/supervisor/scripts/can.py", line 3
    def set_id_filter(socket zmq.Socket, filters):
                               ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "scripts/node2.py", line 4, in <module>
    import can
  File "/home/nebu/supervisor/scripts/can.py", line 3
    def set_id_filter(socket zmq.Socket, filters):
                               ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "scripts/node2.py", line 4, in <module>
    import can
  File "/home/nebu/supervisor/scripts/can.py", line 3
    def set_id_filter(socket zmq.Socket, filters):
                               ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "scripts/node2.py", line 4, in <module>
    import can
  File "/home/nebu/supervisor/scripts/can.py", line 3
    def set_id_filter(socket zmq.Socket, filters):
                               ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "scripts/node2.py", line 4, in <module>
    import can
  File "/home/nebu/supervisor/scripts/can.py", line 3
    def set_id_filter(socket zmq.Socket, filters):
                               ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "scripts/node2.py", line 4, in <module>
    import can
  File "/home/nebu/supervisor/scripts/can.py", line 3
    def set_id_filter(socket zmq.Socket, filters):
                               ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "scripts/node2.py", line 4, in <module>
    import can
  File "/home/nebu/supervisor/scripts/can.py", line 3
    def set_id_filter(socket zmq.Socket, filters):
                               ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "scripts/node2.py", line 4, in <module>
    import can
  File "/home/nebu/supervisor/scripts/can.py", line 3
    def set_id_filter(socket zmq.Socket, filters):
                               ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "scripts/node2.py", line 4, in <module>
    import can
  File "/home/nebu/supervisor/scripts/can.py", line 3
    def set_id_filter(zmq.Socket, filters):
                         ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "scripts/node2.py", line 4, in <module>
    import can
  File "/home/nebu/supervisor/scripts/can.py", line 3
    def set_id_filter(zmq.Socket, filters):
                         ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "scripts/node2.py", line 4, in <module>
    import can
  File "/home/nebu/supervisor/scripts/can.py", line 3
    def set_id_filter(zmq.Socket, filters):
                         ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "scripts/node2.py", line 4, in <module>
    import can
  File "/home/nebu/supervisor/scripts/can.py", line 3
    def set_id_filter(zmq.Socket, filters):
                         ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "scripts/node2.py", line 4, in <module>
    import can
  File "/home/nebu/supervisor/scripts/can.py", line 3
    def set_id_filter(zmq.Socket, filters):
                         ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "scripts/node2.py", line 4, in <module>
    import can
  File "/home/nebu/supervisor/scripts/can.py", line 3
    def set_id_filter(zmq.Socket, filters):
                         ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "scripts/node2.py", line 4, in <module>
    import can
  File "/home/nebu/supervisor/scripts/can.py", line 3
    def set_id_filter(zmq.Socket, filters):
                         ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "scripts/node2.py", line 4, in <module>
    import can
  File "/home/nebu/supervisor/scripts/can.py", line 3
    def set_id_filter(zmq.Socket, filters):
                         ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "scripts/node2.py", line 4, in <module>
    import can
  File "/home/nebu/supervisor/scripts/can.py", line 3
    def set_id_filter(zmq.Socket, filters):
                         ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "scripts/node2.py", line 4, in <module>
    import can
  File "/home/nebu/supervisor/scripts/can.py", line 3
    def set_id_filter(zmq.Socket, filters):
                         ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "scripts/node2.py", line 4, in <module>
    import can
  File "/home/nebu/supervisor/scripts/can.py", line 5
    def init_sender() :
      ^
IndentationError: expected an indented block
Traceback (most recent call last):
  File "scripts/node2.py", line 4, in <module>
    import can
  File "/home/nebu/supervisor/scripts/can.py", line 5
    def init_sender() :
      ^
IndentationError: expected an indented block
Traceback (most recent call last):
  File "scripts/node2.py", line 4, in <module>
    import can
  File "/home/nebu/supervisor/scripts/can.py", line 5
    def init_sender() :
      ^
IndentationError: expected an indented block
Traceback (most recent call last):
  File "scripts/node2.py", line 4, in <module>
    import can
  File "/home/nebu/supervisor/scripts/can.py", line 5
    def init_sender() :
      ^
IndentationError: expected an indented block
Traceback (most recent call last):
  File "scripts/node2.py", line 4, in <module>
    import can
  File "/home/nebu/supervisor/scripts/can.py", line 5
    def init_sender() :
      ^
IndentationError: expected an indented block
Traceback (most recent call last):
  File "scripts/node2.py", line 4, in <module>
    import can
  File "/home/nebu/supervisor/scripts/can.py", line 5
    def init_sender() :
      ^
IndentationError: expected an indented block
Traceback (most recent call last):
  File "scripts/node2.py", line 4, in <module>
    import can
  File "/home/nebu/supervisor/scripts/can.py", line 5
    def init_sender() :
      ^
IndentationError: expected an indented block
Traceback (most recent call last):
  File "scripts/node2.py", line 4, in <module>
    import can
  File "/home/nebu/supervisor/scripts/can.py", line 5
    def init_sender() :
      ^
IndentationError: expected an indented block
Traceback (most recent call last):
  File "scripts/node2.py", line 4, in <module>
    import can
  File "/home/nebu/supervisor/scripts/can.py", line 5
    def init_sender() :
      ^
IndentationError: expected an indented block
Traceback (most recent call last):
  File "scripts/node2.py", line 4, in <module>
    import can
  File "/home/nebu/supervisor/scripts/can.py", line 5
    def init_sender() :
      ^
IndentationError: expected an indented block
Traceback (most recent call last):
  File "scripts/node2.py", line 4, in <module>
    import can
  File "/home/nebu/supervisor/scripts/can.py", line 5
    def init_sender() :
      ^
IndentationError: expected an indented block
Traceback (most recent call last):
  File "scripts/node2.py", line 4, in <module>
    import can
  File "/home/nebu/supervisor/scripts/can.py", line 5
    def init_sender() :
      ^
IndentationError: expected an indented block
Traceback (most recent call last):
  File "scripts/node2.py", line 4, in <module>
    import can
  File "/home/nebu/supervisor/scripts/can.py", line 5
    def init_sender() :
      ^
IndentationError: expected an indented block
Traceback (most recent call last):
  File "scripts/node2.py", line 4, in <module>
    import can
  File "/home/nebu/supervisor/scripts/can.py", line 5
    def init_sender() :
      ^
IndentationError: expected an indented block
Traceback (most recent call last):
  File "scripts/node2.py", line 4, in <module>
    import can
  File "/home/nebu/supervisor/scripts/can.py", line 5
    def init_sender() :
      ^
IndentationError: expected an indented block
Traceback (most recent call last):
  File "scripts/node2.py", line 4, in <module>
    import can
  File "/home/nebu/supervisor/scripts/can.py", line 5
    def init_sender() :
      ^
IndentationError: expected an indented block
Traceback (most recent call last):
  File "scripts/node2.py", line 4, in <module>
    import can
  File "/home/nebu/supervisor/scripts/can.py", line 5
    def init_sender() :
      ^
IndentationError: expected an indented block
Traceback (most recent call last):
  File "scripts/node2.py", line 4, in <module>
    import can
  File "/home/nebu/supervisor/scripts/can.py", line 5
    def init_sender() :
      ^
IndentationError: expected an indented block
Traceback (most recent call last):
  File "scripts/node2.py", line 41, in <module>
    main()
  File "scripts/node2.py", line 17, in main
    receiver = can.init_receiver()
TypeError: init_receiver() takes exactly 1 argument (0 given)
Traceback (most recent call last):
  File "scripts/node2.py", line 41, in <module>
    main()
  File "scripts/node2.py", line 17, in main
    receiver = can.init_receiver()
TypeError: init_receiver() takes exactly 1 argument (0 given)
Traceback (most recent call last):
  File "scripts/node2.py", line 41, in <module>
    main()
  File "scripts/node2.py", line 17, in main
    receiver = can.init_receiver()
TypeError: init_receiver() takes exactly 1 argument (0 given)
Traceback (most recent call last):
  File "scripts/node2.py", line 41, in <module>
    main()
  File "scripts/node2.py", line 17, in main
    receiver = can.init_receiver()
TypeError: init_receiver() takes exactly 1 argument (0 given)
Traceback (most recent call last):
  File "scripts/node2.py", line 41, in <module>
    main()
  File "scripts/node2.py", line 17, in main
    receiver = can.init_receiver()
TypeError: init_receiver() takes exactly 1 argument (0 given)
Traceback (most recent call last):
  File "scripts/node2.py", line 41, in <module>
    main()
  File "scripts/node2.py", line 17, in main
    receiver = can.init_receiver()
TypeError: init_receiver() takes exactly 1 argument (0 given)
Traceback (most recent call last):
  File "scripts/node2.py", line 41, in <module>
    main()
  File "scripts/node2.py", line 17, in main
    receiver = can.init_receiver()
  File "/home/nebu/supervisor/scripts/can.py", line 19, in init_receiver
    receiver.setsockopt(zmq.SUBSCRIBE, id_filter)
  File "zmq/backend/cython/socket.pyx", line 372, in zmq.backend.cython.socket.Socket.set (zmq/backend/cython/socket.c:4208)
TypeError: not enough arguments for format string
Traceback (most recent call last):
  File "scripts/node2.py", line 41, in <module>
    main()
  File "scripts/node2.py", line 17, in main
    receiver = can.init_receiver()
  File "/home/nebu/supervisor/scripts/can.py", line 19, in init_receiver
    receiver.setsockopt(zmq.SUBSCRIBE, id_filter)
  File "zmq/backend/cython/socket.pyx", line 372, in zmq.backend.cython.socket.Socket.set (zmq/backend/cython/socket.c:4208)
TypeError: not enough arguments for format string
Traceback (most recent call last):
  File "scripts/node2.py", line 41, in <module>
    main()
  File "scripts/node2.py", line 17, in main
    receiver = can.init_receiver()
  File "/home/nebu/supervisor/scripts/can.py", line 19, in init_receiver
    receiver.setsockopt(zmq.SUBSCRIBE, id_filter)
  File "zmq/backend/cython/socket.pyx", line 372, in zmq.backend.cython.socket.Socket.set (zmq/backend/cython/socket.c:4208)
TypeError: not enough arguments for format string
Traceback (most recent call last):
  File "scripts/node2.py", line 41, in <module>
    main()
  File "scripts/node2.py", line 17, in main
    receiver = can.init_receiver()
  File "/home/nebu/supervisor/scripts/can.py", line 19, in init_receiver
    receiver.setsockopt(zmq.SUBSCRIBE, id_filter)
  File "zmq/backend/cython/socket.pyx", line 372, in zmq.backend.cython.socket.Socket.set (zmq/backend/cython/socket.c:4208)
TypeError: not enough arguments for format string
Traceback (most recent call last):
  File "scripts/node2.py", line 41, in <module>
    main()
  File "scripts/node2.py", line 17, in main
    receiver = can.init_receiver()
  File "/home/nebu/supervisor/scripts/can.py", line 19, in init_receiver
    receiver.setsockopt(zmq.SUBSCRIBE, id_filter)
  File "zmq/backend/cython/socket.pyx", line 372, in zmq.backend.cython.socket.Socket.set (zmq/backend/cython/socket.c:4208)
TypeError: not enough arguments for format string
Traceback (most recent call last):
  File "scripts/node2.py", line 41, in <module>
    main()
  File "scripts/node2.py", line 17, in main
    receiver = can.init_receiver()
  File "/home/nebu/supervisor/scripts/can.py", line 19, in init_receiver
    receiver.setsockopt(zmq.SUBSCRIBE, id_filter)
  File "zmq/backend/cython/socket.pyx", line 372, in zmq.backend.cython.socket.Socket.set (zmq/backend/cython/socket.c:4208)
TypeError: not enough arguments for format string
Traceback (most recent call last):
  File "scripts/node2.py", line 41, in <module>
    main()
  File "scripts/node2.py", line 17, in main
    receiver = can.init_receiver()
  File "/home/nebu/supervisor/scripts/can.py", line 19, in init_receiver
    receiver.setsockopt(zmq.SUBSCRIBE, id_filter)
  File "zmq/backend/cython/socket.pyx", line 372, in zmq.backend.cython.socket.Socket.set (zmq/backend/cython/socket.c:4208)
TypeError: not enough arguments for format string
Traceback (most recent call last):
  File "scripts/node2.py", line 41, in <module>
    main()
  File "scripts/node2.py", line 17, in main
    receiver = can.init_receiver()
  File "/home/nebu/supervisor/scripts/can.py", line 19, in init_receiver
    receiver.setsockopt(zmq.SUBSCRIBE, id_filter)
  File "zmq/backend/cython/socket.pyx", line 372, in zmq.backend.cython.socket.Socket.set (zmq/backend/cython/socket.c:4208)
TypeError: not enough arguments for format string
Traceback (most recent call last):
  File "scripts/node2.py", line 41, in <module>
    main()
  File "scripts/node2.py", line 17, in main
    receiver = can.init_receiver()
  File "/home/nebu/supervisor/scripts/can.py", line 19, in init_receiver
    receiver.setsockopt(zmq.SUBSCRIBE, id_filter)
  File "zmq/backend/cython/socket.pyx", line 372, in zmq.backend.cython.socket.Socket.set (zmq/backend/cython/socket.c:4208)
TypeError: not enough arguments for format string
Traceback (most recent call last):
  File "scripts/node2.py", line 41, in <module>
    main()
  File "scripts/node2.py", line 17, in main
    receiver = can.init_receiver()
  File "/home/nebu/supervisor/scripts/can.py", line 19, in init_receiver
    receiver.setsockopt(zmq.SUBSCRIBE, id_filter)
  File "zmq/backend/cython/socket.pyx", line 372, in zmq.backend.cython.socket.Socket.set (zmq/backend/cython/socket.c:4208)
TypeError: not enough arguments for format string
Traceback (most recent call last):
  File "scripts/node2.py", line 41, in <module>
    main()
  File "scripts/node2.py", line 17, in main
    receiver = can.init_receiver()
  File "/home/nebu/supervisor/scripts/can.py", line 19, in init_receiver
    receiver.setsockopt(zmq.SUBSCRIBE, id_filter)
  File "zmq/backend/cython/socket.pyx", line 372, in zmq.backend.cython.socket.Socket.set (zmq/backend/cython/socket.c:4208)
TypeError: not enough arguments for format string
Traceback (most recent call last):
  File "scripts/node2.py", line 41, in <module>
    main()
  File "scripts/node2.py", line 17, in main
    receiver = can.init_receiver()
  File "/home/nebu/supervisor/scripts/can.py", line 19, in init_receiver
    receiver.setsockopt(zmq.SUBSCRIBE, id_filter)
  File "zmq/backend/cython/socket.pyx", line 372, in zmq.backend.cython.socket.Socket.set (zmq/backend/cython/socket.c:4208)
TypeError: not enough arguments for format string
Traceback (most recent call last):
  File "scripts/node2.py", line 41, in <module>
    main()
  File "scripts/node2.py", line 17, in main
    receiver = can.init_receiver()
  File "/home/nebu/supervisor/scripts/can.py", line 19, in init_receiver
    receiver.setsockopt(zmq.SUBSCRIBE, id_filter)
  File "zmq/backend/cython/socket.pyx", line 372, in zmq.backend.cython.socket.Socket.set (zmq/backend/cython/socket.c:4208)
TypeError: not enough arguments for format string
Traceback (most recent call last):
  File "scripts/node2.py", line 41, in <module>
    main()
  File "scripts/node2.py", line 17, in main
    receiver = can.init_receiver()
  File "/home/nebu/supervisor/scripts/can.py", line 19, in init_receiver
    receiver.setsockopt(zmq.SUBSCRIBE, id_filter)
  File "zmq/backend/cython/socket.pyx", line 372, in zmq.backend.cython.socket.Socket.set (zmq/backend/cython/socket.c:4208)
TypeError: not enough arguments for format string
Traceback (most recent call last):
  File "scripts/node2.py", line 41, in <module>
    main()
  File "scripts/node2.py", line 17, in main
    receiver = can.init_receiver()
  File "/home/nebu/supervisor/scripts/can.py", line 19, in init_receiver
    receiver.setsockopt(zmq.SUBSCRIBE, id_filter)
  File "zmq/backend/cython/socket.pyx", line 372, in zmq.backend.cython.socket.Socket.set (zmq/backend/cython/socket.c:4208)
TypeError: not enough arguments for format string
Traceback (most recent call last):
  File "scripts/node2.py", line 41, in <module>
    main()
  File "scripts/node2.py", line 17, in main
    receiver = can.init_receiver()
TypeError: init_receiver() takes exactly 1 argument (0 given)
Traceback (most recent call last):
  File "scripts/node2.py", line 41, in <module>
    main()
  File "scripts/node2.py", line 17, in main
    receiver = can.init_receiver()
TypeError: init_receiver() takes exactly 1 argument (0 given)
Traceback (most recent call last):
  File "scripts/node2.py", line 41, in <module>
    main()
  File "scripts/node2.py", line 17, in main
    receiver = can.init_receiver()
TypeError: init_receiver() takes exactly 1 argument (0 given)
Traceback (most recent call last):
  File "scripts/node2.py", line 41, in <module>
    main()
  File "scripts/node2.py", line 18, in main
    can.set_message_filters(receiver, id_filter)
  File "/home/nebu/supervisor/scripts/can.py", line 27, in set_message_filters
    socket.setsockotp(zmq.SUBSCRIBE, f)
  File "/usr/local/lib/python2.7/dist-packages/pyzmq-15.1.0-py2.7-linux-x86_64.egg/zmq/sugar/attrsettr.py", line 42, in __getattr__
    self.__class__.__name__, upper_key)
AttributeError: Socket has no such option: SETSOCKOTP
Traceback (most recent call last):
  File "scripts/node2.py", line 41, in <module>
    main()
  File "scripts/node2.py", line 18, in main
    can.set_message_filters(receiver, id_filter)
  File "/home/nebu/supervisor/scripts/can.py", line 27, in set_message_filters
    socket.setsockotp(zmq.SUBSCRIBE, f)
  File "/usr/local/lib/python2.7/dist-packages/pyzmq-15.1.0-py2.7-linux-x86_64.egg/zmq/sugar/attrsettr.py", line 42, in __getattr__
    self.__class__.__name__, upper_key)
AttributeError: Socket has no such option: SETSOCKOTP
Traceback (most recent call last):
  File "scripts/node2.py", line 41, in <module>
    main()
  File "scripts/node2.py", line 18, in main
    can.set_message_filters(receiver, id_filter)
  File "/home/nebu/supervisor/scripts/can.py", line 27, in set_message_filters
    socket.setsockotp(zmq.SUBSCRIBE, f)
  File "/usr/local/lib/python2.7/dist-packages/pyzmq-15.1.0-py2.7-linux-x86_64.egg/zmq/sugar/attrsettr.py", line 42, in __getattr__
    self.__class__.__name__, upper_key)
AttributeError: Socket has no such option: SETSOCKOTP
Traceback (most recent call last):
  File "scripts/node2.py", line 41, in <module>
    main()
  File "scripts/node2.py", line 18, in main
    can.set_message_filters(receiver, id_filter)
  File "/home/nebu/supervisor/scripts/can.py", line 27, in set_message_filters
    socket.setsockotp(zmq.SUBSCRIBE, f)
  File "/usr/local/lib/python2.7/dist-packages/pyzmq-15.1.0-py2.7-linux-x86_64.egg/zmq/sugar/attrsettr.py", line 42, in __getattr__
    self.__class__.__name__, upper_key)
AttributeError: Socket has no such option: SETSOCKOTP
Traceback (most recent call last):
  File "scripts/node2.py", line 42, in <module>
    main()
  File "scripts/node2.py", line 17, in main
    receiver = can.init_receiver(2)
  File "/home/nebu/supervisor/scripts/can.py", line 19, in init_receiver
    receiver.setsockopt(zmq.SUBSCRIBE, id_filter)
  File "zmq/backend/cython/socket.pyx", line 372, in zmq.backend.cython.socket.Socket.set (zmq/backend/cython/socket.c:4220)
TypeError: expected bytes, got: 2
Traceback (most recent call last):
  File "scripts/node2.py", line 42, in <module>
    main()
  File "scripts/node2.py", line 17, in main
    receiver = can.init_receiver(2)
  File "/home/nebu/supervisor/scripts/can.py", line 19, in init_receiver
    receiver.setsockopt(zmq.SUBSCRIBE, id_filter)
  File "zmq/backend/cython/socket.pyx", line 372, in zmq.backend.cython.socket.Socket.set (zmq/backend/cython/socket.c:4220)
TypeError: expected bytes, got: 2
Traceback (most recent call last):
  File "scripts/node2.py", line 42, in <module>
    main()
  File "scripts/node2.py", line 17, in main
    receiver = can.init_receiver(2)
  File "/home/nebu/supervisor/scripts/can.py", line 19, in init_receiver
    receiver.setsockopt(zmq.SUBSCRIBE, id_filter)
  File "zmq/backend/cython/socket.pyx", line 372, in zmq.backend.cython.socket.Socket.set (zmq/backend/cython/socket.c:4220)
TypeError: expected bytes, got: 2
Traceback (most recent call last):
  File "scripts/node2.py", line 42, in <module>
    main()
  File "scripts/node2.py", line 17, in main
    receiver = can.init_receiver(2)
  File "/home/nebu/supervisor/scripts/can.py", line 19, in init_receiver
    receiver.setsockopt(zmq.SUBSCRIBE, id_filter)
  File "zmq/backend/cython/socket.pyx", line 372, in zmq.backend.cython.socket.Socket.set (zmq/backend/cython/socket.c:4220)
TypeError: expected bytes, got: 2
Traceback (most recent call last):
  File "scripts/node2.py", line 42, in <module>
    main()
  File "scripts/node2.py", line 20, in main
    can.set_message_filters(receiver, id_filter)
  File "/home/nebu/supervisor/scripts/can.py", line 32, in set_message_filters
    print_out(f)
  File "/home/nebu/supervisor/scripts/can.py", line 4, in print_out
    sys.stdout.write( str )
NameError: global name 'sys' is not defined
Traceback (most recent call last):
  File "scripts/node2.py", line 42, in <module>
    main()
  File "scripts/node2.py", line 20, in main
    can.set_message_filters(receiver, id_filter)
  File "/home/nebu/supervisor/scripts/can.py", line 32, in set_message_filters
    print_out(f)
  File "/home/nebu/supervisor/scripts/can.py", line 4, in print_out
    sys.stdout.write( str )
NameError: global name 'sys' is not defined
Traceback (most recent call last):
  File "scripts/node2.py", line 42, in <module>
    main()
  File "scripts/node2.py", line 20, in main
    can.set_message_filters(receiver, id_filter)
  File "/home/nebu/supervisor/scripts/can.py", line 32, in set_message_filters
    print_out(f)
  File "/home/nebu/supervisor/scripts/can.py", line 4, in print_out
    sys.stdout.write( str )
NameError: global name 'sys' is not defined
Traceback (most recent call last):
  File "scripts/node2.py", line 45, in <module>
    main()
  File "scripts/node2.py", line 23, in main
    socket.setsocktopt(zmq.SUBSCRIBE, i)
NameError: global name 'socket' is not defined
Traceback (most recent call last):
  File "scripts/node2.py", line 45, in <module>
    main()
  File "scripts/node2.py", line 23, in main
    socket.setsocktopt(zmq.SUBSCRIBE, i)
NameError: global name 'socket' is not defined
Traceback (most recent call last):
  File "scripts/node2.py", line 45, in <module>
    main()
  File "scripts/node2.py", line 23, in main
    socket.setsocktopt(zmq.SUBSCRIBE, i)
NameError: global name 'socket' is not defined
Traceback (most recent call last):
  File "scripts/node2.py", line 45, in <module>
    main()
  File "scripts/node2.py", line 23, in main
    receiver.setsocktopt(zmq.SUBSCRIBE, i)
  File "/usr/local/lib/python2.7/dist-packages/pyzmq-15.1.0-py2.7-linux-x86_64.egg/zmq/sugar/attrsettr.py", line 42, in __getattr__
    self.__class__.__name__, upper_key)
AttributeError: Socket has no such option: SETSOCKTOPT
Traceback (most recent call last):
  File "scripts/node2.py", line 45, in <module>
    main()
  File "scripts/node2.py", line 23, in main
    receiver.setsocktopt(zmq.SUBSCRIBE, i)
  File "/usr/local/lib/python2.7/dist-packages/pyzmq-15.1.0-py2.7-linux-x86_64.egg/zmq/sugar/attrsettr.py", line 42, in __getattr__
    self.__class__.__name__, upper_key)
AttributeError: Socket has no such option: SETSOCKTOPT
Traceback (most recent call last):
  File "scripts/node2.py", line 45, in <module>
    main()
  File "scripts/node2.py", line 23, in main
    receiver.setsocktopt(zmq.SUBSCRIBE, i)
  File "/usr/local/lib/python2.7/dist-packages/pyzmq-15.1.0-py2.7-linux-x86_64.egg/zmq/sugar/attrsettr.py", line 42, in __getattr__
    self.__class__.__name__, upper_key)
AttributeError: Socket has no such option: SETSOCKTOPT
Traceback (most recent call last):
  File "scripts/node2.py", line 42, in <module>
    main()
  File "scripts/node2.py", line 17, in main
    receiver = can.init_receiver()
  File "/home/nebu/supervisor/scripts/can.py", line 25, in init_receiver
    receiver.setsockopt(zmq.SUBSCRIBE, id_filter)
NameError: global name 'id_filter' is not defined
Traceback (most recent call last):
  File "scripts/node2.py", line 42, in <module>
    main()
  File "scripts/node2.py", line 17, in main
    receiver = can.init_receiver()
  File "/home/nebu/supervisor/scripts/can.py", line 25, in init_receiver
    receiver.setsockopt(zmq.SUBSCRIBE, id_filter)
NameError: global name 'id_filter' is not defined
Traceback (most recent call last):
  File "scripts/node2.py", line 42, in <module>
    main()
  File "scripts/node2.py", line 17, in main
    receiver = can.init_receiver()
  File "/home/nebu/supervisor/scripts/can.py", line 25, in init_receiver
    receiver.setsockopt(zmq.SUBSCRIBE, id_filter)
NameError: global name 'id_filter' is not defined
Traceback (most recent call last):
  File "scripts/node2.py", line 42, in <module>
    main()
  File "scripts/node2.py", line 17, in main
    receiver = can.init_receiver()
  File "/home/nebu/supervisor/scripts/can.py", line 25, in init_receiver
    receiver.setsockopt(zmq.SUBSCRIBE, id_filter)
NameError: global name 'id_filter' is not defined
Traceback (most recent call last):
  File "scripts/node2.py", line 42, in <module>
    main()
  File "scripts/node2.py", line 17, in main
    receiver = can.init_receiver()
  File "/home/nebu/supervisor/scripts/can.py", line 25, in init_receiver
    receiver.setsockopt(zmq.SUBSCRIBE, id_filter)
NameError: global name 'id_filter' is not defined
Traceback (most recent call last):
  File "scripts/node2.py", line 42, in <module>
    main()
  File "scripts/node2.py", line 17, in main
    receiver = can.init_receiver()
  File "/home/nebu/supervisor/scripts/can.py", line 25, in init_receiver
    receiver.setsockopt(zmq.SUBSCRIBE, id_filter)
NameError: global name 'id_filter' is not defined
Traceback (most recent call last):
  File "scripts/node2.py", line 42, in <module>
    main()
  File "scripts/node2.py", line 17, in main
    receiver = can.init_receiver()
  File "/home/nebu/supervisor/scripts/can.py", line 25, in init_receiver
    receiver.setsockopt(zmq.SUBSCRIBE, id_filter)
NameError: global name 'id_filter' is not defined
Traceback (most recent call last):
  File "scripts/node2.py", line 42, in <module>
    main()
  File "scripts/node2.py", line 17, in main
    receiver = can.init_receiver()
  File "/home/nebu/supervisor/scripts/can.py", line 25, in init_receiver
    receiver.setsockopt(zmq.SUBSCRIBE, id_filter)
NameError: global name 'id_filter' is not defined
Traceback (most recent call last):
  File "scripts/node2.py", line 42, in <module>
    main()
  File "scripts/node2.py", line 17, in main
    receiver = can.init_receiver()
  File "/home/nebu/supervisor/scripts/can.py", line 25, in init_receiver
    receiver.setsockopt(zmq.SUBSCRIBE, id_filter)
NameError: global name 'id_filter' is not defined
Traceback (most recent call last):
  File "scripts/node2.py", line 42, in <module>
    main()
  File "scripts/node2.py", line 17, in main
    receiver = can.init_receiver()
  File "/home/nebu/supervisor/scripts/can.py", line 25, in init_receiver
    receiver.setsockopt(zmq.SUBSCRIBE, id_filter)
NameError: global name 'id_filter' is not defined
Traceback (most recent call last):
  File "scripts/node2.py", line 42, in <module>
    main()
  File "scripts/node2.py", line 17, in main
    receiver = can.init_receiver()
  File "/home/nebu/supervisor/scripts/can.py", line 25, in init_receiver
    receiver.setsockopt(zmq.SUBSCRIBE, id_filter)
NameError: global name 'id_filter' is not defined
Traceback (most recent call last):
  File "scripts/node2.py", line 42, in <module>
    main()
  File "scripts/node2.py", line 17, in main
    receiver = can.init_receiver()
  File "/home/nebu/supervisor/scripts/can.py", line 25, in init_receiver
    receiver.setsockopt(zmq.SUBSCRIBE, id_filter)
NameError: global name 'id_filter' is not defined
Traceback (most recent call last):
  File "scripts/node2.py", line 42, in <module>
    main()
  File "scripts/node2.py", line 17, in main
    receiver = can.init_receiver()
  File "/home/nebu/supervisor/scripts/can.py", line 25, in init_receiver
    receiver.setsockopt(zmq.SUBSCRIBE, id_filter)
NameError: global name 'id_filter' is not defined
Traceback (most recent call last):
  File "scripts/node2.py", line 42, in <module>
    main()
  File "scripts/node2.py", line 17, in main
    receiver = can.init_receiver()
  File "/home/nebu/supervisor/scripts/can.py", line 25, in init_receiver
    receiver.setsockopt(zmq.SUBSCRIBE, id_filter)
NameError: global name 'id_filter' is not defined
Traceback (most recent call last):
  File "scripts/node2.py", line 42, in <module>
    main()
  File "scripts/node2.py", line 17, in main
    receiver = can.init_receiver()
  File "/home/nebu/supervisor/scripts/can.py", line 25, in init_receiver
    receiver.setsockopt(zmq.SUBSCRIBE, id_filter)
NameError: global name 'id_filter' is not defined
Traceback (most recent call last):
  File "scripts/node2.py", line 42, in <module>
    main()
  File "scripts/node2.py", line 17, in main
    receiver = can.init_receiver()
  File "/home/nebu/supervisor/scripts/can.py", line 25, in init_receiver
    receiver.setsockopt(zmq.SUBSCRIBE, id_filter)
NameError: global name 'id_filter' is not defined
Traceback (most recent call last):
  File "scripts/node2.py", line 42, in <module>
    main()
  File "scripts/node2.py", line 17, in main
    receiver = can.init_receiver()
  File "/home/nebu/supervisor/scripts/can.py", line 25, in init_receiver
    receiver.setsockopt(zmq.SUBSCRIBE, id_filter)
NameError: global name 'id_filter' is not defined
Traceback (most recent call last):
  File "scripts/node2.py", line 42, in <module>
    main()
  File "scripts/node2.py", line 17, in main
    receiver = can.init_receiver()
  File "/home/nebu/supervisor/scripts/can.py", line 25, in init_receiver
    receiver.setsockopt(zmq.SUBSCRIBE, id_filter)
NameError: global name 'id_filter' is not defined
Traceback (most recent call last):
  File "scripts/node2.py", line 42, in <module>
    main()
  File "scripts/node2.py", line 17, in main
    receiver = can.init_receiver()
  File "/home/nebu/supervisor/scripts/can.py", line 25, in init_receiver
    receiver.setsockopt(zmq.SUBSCRIBE, id_filter)
NameError: global name 'id_filter' is not defined
Traceback (most recent call last):
  File "scripts/node2.py", line 39, in <module>
    main()
  File "scripts/node2.py", line 23, in main
    print_out( "This is node 2" )
NameError: global name 'print_out' is not defined
Traceback (most recent call last):
  File "scripts/node2.py", line 39, in <module>
    main()
  File "scripts/node2.py", line 23, in main
    print_out( "This is node 2" )
NameError: global name 'print_out' is not defined
Traceback (most recent call last):
  File "scripts/node2.py", line 39, in <module>
    main()
  File "scripts/node2.py", line 23, in main
    print_out( "This is node 2" )
NameError: global name 'print_out' is not defined
  File "scripts/node2.py", line 36
    msg_id, data = can_message.split(' ', 1)
         ^
IndentationError: expected an indented block
  File "scripts/node2.py", line 36
    msg_id, data = can_message.split(' ', 1)
         ^
IndentationError: expected an indented block
  File "scripts/node2.py", line 36
    msg_id, data = can_message.split(' ', 1)
         ^
IndentationError: expected an indented block
  File "scripts/node2.py", line 36
    msg_id, data = can_message.split(' ', 1)
         ^
IndentationError: expected an indented block
  File "scripts/node2.py", line 36
    msg_id, data = can_message.split(' ', 1)
         ^
IndentationError: expected an indented block
  File "scripts/node2.py", line 36
    msg_id, data = can_message.split(' ', 1)
         ^
IndentationError: expected an indented block
  File "scripts/node2.py", line 36
    msg_id, data = can_message.split(' ', 1)
         ^
IndentationError: expected an indented block
  File "scripts/node2.py", line 36
    msg_id, data = can_message.split(' ', 1)
         ^
IndentationError: expected an indented block
  File "scripts/node2.py", line 36
    msg_id, data = can_message.split(' ', 1)
         ^
IndentationError: expected an indented block
  File "scripts/node2.py", line 36
    msg_id, data = can_message.split(' ', 1)
         ^
IndentationError: expected an indented block
  File "scripts/node2.py", line 36
    msg_id, data = can_message.split(' ', 1)
         ^
IndentationError: expected an indented block
  File "scripts/node2.py", line 36
    msg_id, data = can_message.split(' ', 1)
         ^
IndentationError: expected an indented block
  File "scripts/node2.py", line 36
    msg_id, data = can_message.split(' ', 1)
         ^
IndentationError: expected an indented block
  File "scripts/node2.py", line 36
    msg_id, data = can_message.split(' ', 1)
         ^
IndentationError: expected an indented block
  File "scripts/node2.py", line 36
    msg_id, data = can_message.split(' ', 1)
         ^
IndentationError: expected an indented block
  File "scripts/node2.py", line 36
    msg_id, data = can_message.split(' ', 1)
         ^
IndentationError: expected an indented block
  File "scripts/node2.py", line 36
    msg_id, data = can_message.split(' ', 1)
         ^
IndentationError: expected an indented block
  File "scripts/node2.py", line 36
    msg_id, data = can_message.split(' ', 1)
         ^
IndentationError: expected an indented block
  File "scripts/node2.py", line 36
    msg_id, data = can_message.split(' ', 1)
         ^
IndentationError: expected an indented block
  File "scripts/node2.py", line 36
    msg_id, data = can_message.split(' ', 1)
         ^
IndentationError: expected an indented block
  File "scripts/node2.py", line 36
    msg_id, data = can_message.split(' ', 1)
         ^
IndentationError: expected an indented block
  File "scripts/node2.py", line 36
    msg_id, data = can_message.split(' ', 1)
         ^
IndentationError: expected an indented block
  File "scripts/node2.py", line 36
    msg_id, data = can_message.split(' ', 1)
         ^
IndentationError: expected an indented block
  File "scripts/node2.py", line 36
    msg_id, data = can_message.split(' ', 1)
         ^
IndentationError: expected an indented block
  File "scripts/node2.py", line 36
    msg_id, data = can_message.split(' ', 1)
         ^
IndentationError: expected an indented block
  File "scripts/node2.py", line 36
    msg_id, data = can_message.split(' ', 1)
         ^
IndentationError: expected an indented block
  File "scripts/node2.py", line 36
    msg_id, data = can_message.split(' ', 1)
         ^
IndentationError: expected an indented block
  File "scripts/node2.py", line 36
    msg_id, data = can_message.split(' ', 1)
         ^
IndentationError: expected an indented block
  File "scripts/node2.py", line 36
    msg_id, data = can_message.split(' ', 1)
         ^
IndentationError: expected an indented block
  File "scripts/node2.py", line 36
    msg_id, data = can_message.split(' ', 1)
         ^
IndentationError: expected an indented block
  File "scripts/node2.py", line 36
    msg_id, data = can_message.split(' ', 1)
         ^
IndentationError: expected an indented block
  File "scripts/node2.py", line 36
    msg_id, data = can_message.split(' ', 1)
         ^
IndentationError: expected an indented block
  File "scripts/node2.py", line 36
    msg_id, data = can_message.split(' ', 1)
         ^
IndentationError: expected an indented block
  File "scripts/node2.py", line 36
    msg_id, data = can_message.split(' ', 1)
         ^
IndentationError: expected an indented block
  File "scripts/node2.py", line 36
    msg_id, data = can_message.split(' ', 1)
         ^
IndentationError: expected an indented block
  File "scripts/node2.py", line 36
    msg_id, data = can_message.split(' ', 1)
         ^
IndentationError: expected an indented block
  File "scripts/node2.py", line 36
    msg_id, data = can_message.split(' ', 1)
         ^
IndentationError: expected an indented block
  File "scripts/node2.py", line 36
    msg_id, data = can_message.split(' ', 1)
         ^
IndentationError: expected an indented block
  File "scripts/node2.py", line 36
    msg_id, data = can_message.split(' ', 1)
         ^
IndentationError: expected an indented block
  File "scripts/node2.py", line 36
    msg_id, data = can_message.split(' ', 1)
         ^
IndentationError: expected an indented block
  File "scripts/node2.py", line 36
    msg_id, data = can_message.split(' ', 1)
         ^
IndentationError: expected an indented block
  File "scripts/node2.py", line 36
    msg_id, data = can_message.split(' ', 1)
         ^
IndentationError: expected an indented block
  File "scripts/node2.py", line 36
    msg_id, data = can_message.split(' ', 1)
         ^
IndentationError: expected an indented block
  File "scripts/node2.py", line 33
    except zmq.core.error.ZMQError,e:
         ^
SyntaxError: invalid syntax
  File "scripts/node2.py", line 33
    except zmq.core.error.ZMQError,e:
         ^
SyntaxError: invalid syntax
  File "scripts/node2.py", line 33
    except zmq.core.error.ZMQError,e:
         ^
SyntaxError: invalid syntax
  File "scripts/node2.py", line 33
    except zmq.core.error.ZMQError,e:
         ^
SyntaxError: invalid syntax
  File "scripts/node2.py", line 33
    except zmq.core.error.ZMQError,e:
         ^
SyntaxError: invalid syntax
  File "scripts/node2.py", line 33
    except zmq.core.error.ZMQError,e:
         ^
SyntaxError: invalid syntax
  File "scripts/node2.py", line 33
    except zmq.core.error.ZMQError,e:
         ^
SyntaxError: invalid syntax
  File "scripts/node2.py", line 33
    except zmq.core.error.ZMQError,e:
         ^
SyntaxError: invalid syntax
  File "scripts/node2.py", line 33
    except zmq.core.error.ZMQError,e:
         ^
SyntaxError: invalid syntax
  File "scripts/node2.py", line 33
    except zmq.core.error.ZMQError,e:
         ^
SyntaxError: invalid syntax
  File "scripts/node2.py", line 33
    except zmq.core.error.ZMQError,e:
         ^
SyntaxError: invalid syntax
  File "scripts/node2.py", line 33
    except zmq.core.error.ZMQError,e:
         ^
SyntaxError: invalid syntax
  File "scripts/node2.py", line 33
    except zmq.core.error.ZMQError,e:
         ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "scripts/node2.py", line 46, in <module>
    main()
  File "scripts/node2.py", line 33, in main
    except zmq.core.error.ZMQError,e:
AttributeError: 'module' object has no attribute 'core'
Traceback (most recent call last):
  File "scripts/node2.py", line 46, in <module>
    main()
  File "scripts/node2.py", line 33, in main
    except zmq.core.error.ZMQError,e:
AttributeError: 'module' object has no attribute 'core'
Traceback (most recent call last):
  File "scripts/node2.py", line 46, in <module>
    main()
  File "scripts/node2.py", line 33, in main
    except zmq.core.error.ZMQError,e:
AttributeError: 'module' object has no attribute 'core'
Traceback (most recent call last):
  File "scripts/node2.py", line 46, in <module>
    main()
  File "scripts/node2.py", line 33, in main
    except zmq.core.error.ZMQError,e:
AttributeError: 'module' object has no attribute 'core'
Traceback (most recent call last):
  File "scripts/node2.py", line 46, in <module>
    main()
  File "scripts/node2.py", line 33, in main
    except zmq.core.error.ZMQError,e:
AttributeError: 'module' object has no attribute 'core'
Traceback (most recent call last):
  File "scripts/node2.py", line 46, in <module>
    main()
  File "scripts/node2.py", line 33, in main
    except zmq.core.error.ZMQError,e:
AttributeError: 'module' object has no attribute 'core'
Traceback (most recent call last):
  File "scripts/node2.py", line 46, in <module>
    main()
  File "scripts/node2.py", line 33, in main
    except zmq.core.error.ZMQError,e:
AttributeError: 'module' object has no attribute 'core'
Traceback (most recent call last):
  File "scripts/node2.py", line 46, in <module>
    main()
  File "scripts/node2.py", line 33, in main
    except zmq.core.error.ZMQError,e:
AttributeError: 'module' object has no attribute 'core'
Traceback (most recent call last):
  File "scripts/node2.py", line 46, in <module>
    main()
  File "scripts/node2.py", line 33, in main
    except zmq.core.error.ZMQError,e:
AttributeError: 'module' object has no attribute 'core'
Traceback (most recent call last):
  File "scripts/node2.py", line 46, in <module>
    main()
  File "scripts/node2.py", line 33, in main
    except zmq.core.error.ZMQError,e:
AttributeError: 'module' object has no attribute 'core'
Traceback (most recent call last):
  File "scripts/node2.py", line 46, in <module>
    main()
  File "scripts/node2.py", line 33, in main
    except zmq.core.error.ZMQError,e:
AttributeError: 'module' object has no attribute 'core'
Traceback (most recent call last):
  File "scripts/node2.py", line 46, in <module>
    main()
  File "scripts/node2.py", line 33, in main
    except zmq.core.error.ZMQError,e:
AttributeError: 'module' object has no attribute 'core'
Traceback (most recent call last):
  File "scripts/node2.py", line 46, in <module>
    main()
  File "scripts/node2.py", line 33, in main
    except zmq.core.error.ZMQError,e:
AttributeError: 'module' object has no attribute 'core'
Traceback (most recent call last):
  File "scripts/node2.py", line 46, in <module>
    main()
  File "scripts/node2.py", line 33, in main
    except zmq.core.error.ZMQError,e:
AttributeError: 'module' object has no attribute 'core'
Traceback (most recent call last):
  File "scripts/node2.py", line 46, in <module>
    main()
  File "scripts/node2.py", line 33, in main
    except zmq.core.error.ZMQError,e:
AttributeError: 'module' object has no attribute 'core'
Traceback (most recent call last):
  File "scripts/node2.py", line 46, in <module>
    main()
  File "scripts/node2.py", line 33, in main
    except zmq.core.error.ZMQError,e:
AttributeError: 'module' object has no attribute 'core'
Traceback (most recent call last):
  File "scripts/node2.py", line 46, in <module>
    main()
  File "scripts/node2.py", line 33, in main
    except zmq.core.error.ZMQError,e:
AttributeError: 'module' object has no attribute 'core'
Traceback (most recent call last):
  File "scripts/node2.py", line 46, in <module>
    main()
  File "scripts/node2.py", line 33, in main
    except zmq.core.error.ZMQError,e:
AttributeError: 'module' object has no attribute 'core'
Traceback (most recent call last):
  File "scripts/node2.py", line 46, in <module>
    main()
  File "scripts/node2.py", line 33, in main
    except zmq.core.error.ZMQError,e:
AttributeError: 'module' object has no attribute 'core'
Traceback (most recent call last):
  File "scripts/node2.py", line 46, in <module>
    main()
  File "scripts/node2.py", line 33, in main
    except zmq.core.error.ZMQError,e:
AttributeError: 'module' object has no attribute 'core'
Traceback (most recent call last):
  File "scripts/node2.py", line 46, in <module>
    main()
  File "scripts/node2.py", line 33, in main
    except zmq.core.error.ZMQError,e:
AttributeError: 'module' object has no attribute 'core'
Traceback (most recent call last):
  File "scripts/node2.py", line 46, in <module>
    main()
  File "scripts/node2.py", line 33, in main
    except zmq.core.error.ZMQError,e:
AttributeError: 'module' object has no attribute 'core'
Traceback (most recent call last):
  File "scripts/node2.py", line 46, in <module>
    main()
  File "scripts/node2.py", line 33, in main
    except zmq.core.error.ZMQError,e:
AttributeError: 'module' object has no attribute 'core'
Traceback (most recent call last):
  File "scripts/node2.py", line 46, in <module>
    main()
  File "scripts/node2.py", line 33, in main
    except zmq.core.error.ZMQError,e:
AttributeError: 'module' object has no attribute 'core'
Traceback (most recent call last):
  File "scripts/node2.py", line 46, in <module>
    main()
  File "scripts/node2.py", line 33, in main
    except zmq.core.error.ZMQError,e:
AttributeError: 'module' object has no attribute 'core'
Traceback (most recent call last):
  File "scripts/node2.py", line 46, in <module>
    main()
  File "scripts/node2.py", line 33, in main
    except e:
NameError: global name 'e' is not defined
Traceback (most recent call last):
  File "scripts/node2.py", line 46, in <module>
    main()
  File "scripts/node2.py", line 33, in main
    except e:
NameError: global name 'e' is not defined
Traceback (most recent call last):
  File "scripts/node2.py", line 46, in <module>
    main()
  File "scripts/node2.py", line 33, in main
    except e:
NameError: global name 'e' is not defined
Traceback (most recent call last):
  File "scripts/node2.py", line 46, in <module>
    main()
  File "scripts/node2.py", line 33, in main
    except e:
NameError: global name 'e' is not defined
Traceback (most recent call last):
  File "scripts/node2.py", line 46, in <module>
    main()
  File "scripts/node2.py", line 32, in main
    can_message = recevSock.recv(flags=zmq.NOBLOCK)
NameError: global name 'recevSock' is not defined
Traceback (most recent call last):
  File "scripts/node2.py", line 46, in <module>
    main()
  File "scripts/node2.py", line 32, in main
    can_message = recevSock.recv(flags=zmq.NOBLOCK)
NameError: global name 'recevSock' is not defined
Traceback (most recent call last):
  File "scripts/node2.py", line 46, in <module>
    main()
  File "scripts/node2.py", line 32, in main
    can_message = recevSock.recv(flags=zmq.NOBLOCK)
NameError: global name 'recevSock' is not defined
Traceback (most recent call last):
  File "scripts/node2.py", line 46, in <module>
    main()
  File "scripts/node2.py", line 32, in main
    can_message = recevSock.recv(flags=zmq.NOBLOCK)
NameError: global name 'recevSock' is not defined
Traceback (most recent call last):
  File "scripts/node2.py", line 46, in <module>
    main()
  File "scripts/node2.py", line 32, in main
    can_message = receiver.recv(flags=zmq.NOBLOCK)
  File "zmq/backend/cython/socket.pyx", line 674, in zmq.backend.cython.socket.Socket.recv (zmq/backend/cython/socket.c:6971)
  File "zmq/backend/cython/socket.pyx", line 708, in zmq.backend.cython.socket.Socket.recv (zmq/backend/cython/socket.c:6763)
  File "zmq/backend/cython/socket.pyx", line 145, in zmq.backend.cython.socket._recv_copy (zmq/backend/cython/socket.c:1931)
  File "zmq/backend/cython/checkrc.pxd", line 19, in zmq.backend.cython.checkrc._check_rc (zmq/backend/cython/socket.c:7384)
zmq.error.Again: Resource temporarily unavailable
Traceback (most recent call last):
  File "scripts/node2.py", line 46, in <module>
    main()
  File "scripts/node2.py", line 32, in main
    can_message = receiver.recv(flags=zmq.NOBLOCK)
  File "zmq/backend/cython/socket.pyx", line 674, in zmq.backend.cython.socket.Socket.recv (zmq/backend/cython/socket.c:6971)
  File "zmq/backend/cython/socket.pyx", line 708, in zmq.backend.cython.socket.Socket.recv (zmq/backend/cython/socket.c:6763)
  File "zmq/backend/cython/socket.pyx", line 145, in zmq.backend.cython.socket._recv_copy (zmq/backend/cython/socket.c:1931)
  File "zmq/backend/cython/checkrc.pxd", line 19, in zmq.backend.cython.checkrc._check_rc (zmq/backend/cython/socket.c:7384)
zmq.error.Again: Resource temporarily unavailable
Traceback (most recent call last):
  File "scripts/node2.py", line 46, in <module>
    main()
  File "scripts/node2.py", line 32, in main
    can_message = receiver.recv(flags=zmq.NOBLOCK)
  File "zmq/backend/cython/socket.pyx", line 674, in zmq.backend.cython.socket.Socket.recv (zmq/backend/cython/socket.c:6971)
  File "zmq/backend/cython/socket.pyx", line 708, in zmq.backend.cython.socket.Socket.recv (zmq/backend/cython/socket.c:6763)
  File "zmq/backend/cython/socket.pyx", line 145, in zmq.backend.cython.socket._recv_copy (zmq/backend/cython/socket.c:1931)
  File "zmq/backend/cython/checkrc.pxd", line 19, in zmq.backend.cython.checkrc._check_rc (zmq/backend/cython/socket.c:7384)
zmq.error.Again: Resource temporarily unavailable
Traceback (most recent call last):
  File "scripts/node2.py", line 46, in <module>
    main()
  File "scripts/node2.py", line 32, in main
    can_message = receiver.recv(flags=zmq.NOBLOCK)
  File "zmq/backend/cython/socket.pyx", line 674, in zmq.backend.cython.socket.Socket.recv (zmq/backend/cython/socket.c:6971)
  File "zmq/backend/cython/socket.pyx", line 708, in zmq.backend.cython.socket.Socket.recv (zmq/backend/cython/socket.c:6763)
  File "zmq/backend/cython/socket.pyx", line 145, in zmq.backend.cython.socket._recv_copy (zmq/backend/cython/socket.c:1931)
  File "zmq/backend/cython/checkrc.pxd", line 19, in zmq.backend.cython.checkrc._check_rc (zmq/backend/cython/socket.c:7384)
zmq.error.Again: Resource temporarily unavailable
Traceback (most recent call last):
  File "scripts/node2.py", line 46, in <module>
    main()
  File "scripts/node2.py", line 37, in main
    msg_id, data = can_message.split(' ', 1)
UnboundLocalError: local variable 'can_message' referenced before assignment
Traceback (most recent call last):
  File "scripts/node2.py", line 46, in <module>
    main()
  File "scripts/node2.py", line 37, in main
    msg_id, data = can_message.split(' ', 1)
UnboundLocalError: local variable 'can_message' referenced before assignment
Traceback (most recent call last):
  File "scripts/node2.py", line 46, in <module>
    main()
  File "scripts/node2.py", line 37, in main
    msg_id, data = can_message.split(' ', 1)
UnboundLocalError: local variable 'can_message' referenced before assignment
Traceback (most recent call last):
  File "scripts/node2.py", line 46, in <module>
    main()
  File "scripts/node2.py", line 37, in main
    msg_id, data = can_message.split(' ', 1)
UnboundLocalError: local variable 'can_message' referenced before assignment
Traceback (most recent call last):
  File "scripts/node2.py", line 46, in <module>
    main()
  File "scripts/node2.py", line 37, in main
    msg_id, data = can_message.split(' ', 1)
UnboundLocalError: local variable 'can_message' referenced before assignment
Traceback (most recent call last):
  File "scripts/node2.py", line 43, in <module>
    main()
  File "scripts/node2.py", line 31, in main
    can_message = can.recv_noblock(receiver)		
  File "/home/nebu/supervisor/scripts/can.py", line 34, in recv_noblock
    can_message = receiver.recv(flags=zmq.NOBLOCK)
NameError: global name 'receiver' is not defined
Traceback (most recent call last):
  File "scripts/node2.py", line 43, in <module>
    main()
  File "scripts/node2.py", line 31, in main
    can_message = can.recv_noblock(receiver)		
  File "/home/nebu/supervisor/scripts/can.py", line 34, in recv_noblock
    can_message = receiver.recv(flags=zmq.NOBLOCK)
NameError: global name 'receiver' is not defined
Traceback (most recent call last):
  File "scripts/node2.py", line 43, in <module>
    main()
  File "scripts/node2.py", line 31, in main
    can_message = can.recv_noblock(receiver)		
  File "/home/nebu/supervisor/scripts/can.py", line 34, in recv_noblock
    can_message = receiver.recv(flags=zmq.NOBLOCK)
NameError: global name 'receiver' is not defined
Traceback (most recent call last):
  File "scripts/node2.py", line 43, in <module>
    main()
  File "scripts/node2.py", line 31, in main
    can_message = can.recv_noblock(receiver)		
  File "/home/nebu/supervisor/scripts/can.py", line 34, in recv_noblock
    can_message = receiver.recv(flags=zmq.NOBLOCK)
NameError: global name 'receiver' is not defined
  File "scripts/node2.py", line 4
    import asdf/canvas
               ^
SyntaxError: invalid syntax
  File "scripts/node2.py", line 4
    import asdf/canvas
               ^
SyntaxError: invalid syntax
  File "scripts/node2.py", line 4
    import asdf/canvas
               ^
SyntaxError: invalid syntax
  File "scripts/node2.py", line 4
    import asdf/canvas
               ^
SyntaxError: invalid syntax
  File "scripts/node2.py", line 4
    import asdf/canvas
               ^
SyntaxError: invalid syntax
  File "scripts/node2.py", line 4
    import asdf/canvas
               ^
SyntaxError: invalid syntax
  File "scripts/node2.py", line 4
    import asdf/canvas
               ^
SyntaxError: invalid syntax
  File "scripts/node2.py", line 4
    import asdf/canvas
               ^
SyntaxError: invalid syntax
  File "scripts/node2.py", line 4
    import asdf/canvas
               ^
SyntaxError: invalid syntax
  File "scripts/node2.py", line 4
    import asdf/canvas
               ^
SyntaxError: invalid syntax
  File "scripts/node2.py", line 4
    import asdf/canvas
               ^
SyntaxError: invalid syntax
  File "scripts/node2.py", line 4
    import asdf/canvas
               ^
SyntaxError: invalid syntax
  File "scripts/node2.py", line 4
    import asdf/canvas
               ^
SyntaxError: invalid syntax
  File "scripts/node2.py", line 4
    import asdf/canvas
               ^
SyntaxError: invalid syntax
  File "scripts/node2.py", line 4
    import asdf/canvas
               ^
SyntaxError: invalid syntax
  File "scripts/node2.py", line 4
    import asdf/canvas
               ^
SyntaxError: invalid syntax
  File "scripts/node2.py", line 4
    import asdf/canvas
               ^
SyntaxError: invalid syntax
  File "scripts/node2.py", line 4
    import asdf/canvas
               ^
SyntaxError: invalid syntax
  File "scripts/node2.py", line 4
    import asdf/canvas
               ^
SyntaxError: invalid syntax
  File "scripts/node2.py", line 4
    import asdf/canvas
               ^
SyntaxError: invalid syntax
  File "scripts/node2.py", line 4
    import asdf/canvas
               ^
SyntaxError: invalid syntax
  File "scripts/node2.py", line 4
    import asdf/canvas
               ^
SyntaxError: invalid syntax
  File "scripts/node2.py", line 4
    import asdf/canvas
               ^
SyntaxError: invalid syntax
  File "scripts/node2.py", line 4
    import asdf/canvas
               ^
SyntaxError: invalid syntax
  File "scripts/node2.py", line 4
    import asdf/canvas
               ^
SyntaxError: invalid syntax
  File "scripts/node2.py", line 4
    import asdf/canvas
               ^
SyntaxError: invalid syntax
  File "scripts/node2.py", line 4
    import asdf/canvas
               ^
SyntaxError: invalid syntax
  File "scripts/node2.py", line 4
    import asdf/canvas
               ^
SyntaxError: invalid syntax
  File "scripts/node2.py", line 4
    import asdf/canvas
               ^
SyntaxError: invalid syntax
  File "scripts/node2.py", line 4
    import asdf/canvas
               ^
SyntaxError: invalid syntax
  File "scripts/node2.py", line 4
    import asdf/canvas
               ^
SyntaxError: invalid syntax
  File "scripts/node2.py", line 4
    import asdf/canvas
               ^
SyntaxError: invalid syntax
  File "scripts/node2.py", line 4
    import asdf/canvas
               ^
SyntaxError: invalid syntax
  File "scripts/node2.py", line 4
    import asdf/canvas
               ^
SyntaxError: invalid syntax
  File "scripts/node2.py", line 4
    import asdf/canvas
               ^
SyntaxError: invalid syntax
  File "scripts/node2.py", line 4
    import asdf/canvas
               ^
SyntaxError: invalid syntax
  File "scripts/node2.py", line 4
    import asdf/canvas
               ^
SyntaxError: invalid syntax
  File "scripts/node2.py", line 4
    import asdf/canvas
               ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "scripts/node2.py", line 4, in <module>
    import asdf.canvas
ImportError: No module named asdf.canvas
Traceback (most recent call last):
  File "scripts/node2.py", line 4, in <module>
    import asdf.canvas
ImportError: No module named asdf.canvas
Traceback (most recent call last):
  File "scripts/node2.py", line 4, in <module>
    import asdf.canvas
ImportError: No module named asdf.canvas
Traceback (most recent call last):
  File "scripts/node2.py", line 4, in <module>
    import asdf.canvas
ImportError: No module named asdf.canvas
Traceback (most recent call last):
  File "scripts/node2.py", line 4, in <module>
    import asdf.canvas
ImportError: No module named asdf.canvas
Traceback (most recent call last):
  File "scripts/node2.py", line 4, in <module>
    import asdf.canvas
ImportError: No module named asdf.canvas
Traceback (most recent call last):
  File "scripts/node2.py", line 4, in <module>
    import asdf.canvas
ImportError: No module named asdf.canvas
Traceback (most recent call last):
  File "scripts/node2.py", line 4, in <module>
    import asdf.canvas
ImportError: No module named asdf.canvas
Traceback (most recent call last):
  File "scripts/node2.py", line 4, in <module>
    import asdf.canvas
ImportError: No module named asdf.canvas
Traceback (most recent call last):
  File "scripts/node2.py", line 4, in <module>
    import asdf.canvas
ImportError: No module named asdf.canvas
Traceback (most recent call last):
  File "scripts/node2.py", line 4, in <module>
    import asdf.canvas
ImportError: No module named asdf.canvas
Traceback (most recent call last):
  File "scripts/node2.py", line 4, in <module>
    import asdf.canvas
ImportError: No module named asdf.canvas
Traceback (most recent call last):
  File "scripts/node2.py", line 4, in <module>
    import asdf.canvas
ImportError: No module named asdf.canvas
Traceback (most recent call last):
  File "scripts/node2.py", line 4, in <module>
    import asdf.canvas
ImportError: No module named asdf.canvas
Traceback (most recent call last):
  File "scripts/node2.py", line 4, in <module>
    import asdf.canvas
ImportError: No module named asdf.canvas
Traceback (most recent call last):
  File "scripts/node2.py", line 7, in <module>
    import canvas
ImportError: No module named canvas
Traceback (most recent call last):
  File "scripts/node2.py", line 7, in <module>
    import canvas
ImportError: No module named canvas
Traceback (most recent call last):
  File "scripts/node2.py", line 7, in <module>
    import canvas
ImportError: No module named canvas
Traceback (most recent call last):
  File "scripts/node2.py", line 7, in <module>
    import canvas
ImportError: No module named canvas
Traceback (most recent call last):
  File "scripts/node2.py", line 7, in <module>
    import canvas
ImportError: No module named canvas
Traceback (most recent call last):
  File "scripts/node2.py", line 7, in <module>
    import canvas
ImportError: No module named canvas
Traceback (most recent call last):
  File "scripts/node2.py", line 7, in <module>
    import canvas
ImportError: No module named canvas
Traceback (most recent call last):
  File "scripts/node2.py", line 7, in <module>
    import canvas
ImportError: No module named canvas
Traceback (most recent call last):
  File "scripts/node2.py", line 7, in <module>
    import canvas
ImportError: No module named canvas
Traceback (most recent call last):
  File "scripts/node2.py", line 7, in <module>
    import canvas
ImportError: No module named canvas
Traceback (most recent call last):
  File "scripts/node2.py", line 7, in <module>
    import canvas
ImportError: No module named canvas
Traceback (most recent call last):
  File "scripts/node2.py", line 7, in <module>
    import canvas
ImportError: No module named canvas
Traceback (most recent call last):
  File "scripts/node2.py", line 7, in <module>
    import canvas
ImportError: No module named canvas
Traceback (most recent call last):
  File "scripts/node2.py", line 7, in <module>
    import canvas
ImportError: No module named canvas
Traceback (most recent call last):
  File "scripts/node2.py", line 7, in <module>
    import canvas
ImportError: No module named canvas
Traceback (most recent call last):
  File "scripts/node2.py", line 7, in <module>
    import canvas
ImportError: No module named canvas
Traceback (most recent call last):
  File "scripts/node2.py", line 7, in <module>
    import canvas
ImportError: No module named canvas
Traceback (most recent call last):
  File "scripts/node2.py", line 7, in <module>
    import canvas
ImportError: No module named canvas
Traceback (most recent call last):
  File "scripts/node2.py", line 7, in <module>
    import canvas
ImportError: No module named canvas
Traceback (most recent call last):
  File "scripts/node2.py", line 7, in <module>
    import canvas
ImportError: No module named canvas
Traceback (most recent call last):
  File "scripts/node2.py", line 7, in <module>
    import canvas
ImportError: No module named canvas
Traceback (most recent call last):
  File "scripts/node2.py", line 7, in <module>
    import canvas
ImportError: No module named canvas
Traceback (most recent call last):
  File "scripts/node2.py", line 7, in <module>
    import canvas
ImportError: No module named canvas
Traceback (most recent call last):
  File "scripts/node2.py", line 7, in <module>
    import canvas
ImportError: No module named canvas
Traceback (most recent call last):
  File "scripts/node2.py", line 7, in <module>
    import canvas
ImportError: No module named canvas
Traceback (most recent call last):
  File "scripts/node2.py", line 7, in <module>
    import canvas
ImportError: No module named canvas
Traceback (most recent call last):
  File "scripts/node2.py", line 7, in <module>
    import canvas
ImportError: No module named canvas
Traceback (most recent call last):
  File "scripts/node2.py", line 7, in <module>
    import canvas
ImportError: No module named canvas
Traceback (most recent call last):
  File "scripts/node2.py", line 7, in <module>
    import canvas
ImportError: No module named canvas
Traceback (most recent call last):
  File "scripts/node2.py", line 7, in <module>
    import canvas
ImportError: No module named canvas
Traceback (most recent call last):
  File "scripts/node2.py", line 7, in <module>
    import canvas
ImportError: No module named canvas
Traceback (most recent call last):
  File "scripts/node2.py", line 7, in <module>
    import canvas
ImportError: No module named canvas
Traceback (most recent call last):
  File "scripts/node2.py", line 7, in <module>
    import canvas
ImportError: No module named canvas
Traceback (most recent call last):
  File "scripts/node2.py", line 7, in <module>
    import canvas
ImportError: No module named canvas
Traceback (most recent call last):
  File "scripts/node2.py", line 7, in <module>
    import canvas
ImportError: No module named canvas
Traceback (most recent call last):
  File "scripts/node2.py", line 7, in <module>
    import canvas
ImportError: No module named canvas
Traceback (most recent call last):
  File "scripts/node2.py", line 7, in <module>
    import canvas
ImportError: No module named canvas
Traceback (most recent call last):
  File "scripts/node2.py", line 7, in <module>
    import canvas
ImportError: No module named canvas
Traceback (most recent call last):
  File "scripts/node2.py", line 7, in <module>
    import canvas
ImportError: No module named canvas
Traceback (most recent call last):
  File "scripts/node2.py", line 8, in <module>
    import canvas
ImportError: No module named canvas
Traceback (most recent call last):
  File "scripts/node2.py", line 8, in <module>
    import canvas
ImportError: No module named canvas
Traceback (most recent call last):
  File "scripts/node2.py", line 8, in <module>
    import canvas
ImportError: No module named canvas
Traceback (most recent call last):
  File "scripts/node2.py", line 8, in <module>
    import canvas
ImportError: No module named canvas
Traceback (most recent call last):
  File "scripts/node2.py", line 8, in <module>
    import canvas
ImportError: No module named canvas
Traceback (most recent call last):
  File "scripts/node2.py", line 8, in <module>
    import canvas
ImportError: No module named canvas
Traceback (most recent call last):
  File "scripts/node2.py", line 8, in <module>
    import canvas
ImportError: No module named canvas
Traceback (most recent call last):
  File "scripts/node2.py", line 8, in <module>
    import canvas
ImportError: No module named canvas
Traceback (most recent call last):
  File "scripts/node2.py", line 8, in <module>
    import canvas
ImportError: No module named canvas
Traceback (most recent call last):
  File "scripts/node2.py", line 8, in <module>
    import canvas
ImportError: No module named canvas
Traceback (most recent call last):
  File "scripts/node2.py", line 8, in <module>
    import canvas
ImportError: No module named canvas
Traceback (most recent call last):
  File "scripts/node2.py", line 8, in <module>
    import canvas
ImportError: No module named canvas
Traceback (most recent call last):
  File "scripts/node2.py", line 8, in <module>
    import canvas
ImportError: No module named canvas
Traceback (most recent call last):
  File "scripts/node2.py", line 8, in <module>
    import canvas
ImportError: No module named canvas
Traceback (most recent call last):
  File "scripts/node2.py", line 8, in <module>
    import canvas
ImportError: No module named canvas
Traceback (most recent call last):
  File "scripts/node2.py", line 8, in <module>
    import canvas
ImportError: No module named canvas
Traceback (most recent call last):
  File "scripts/node2.py", line 8, in <module>
    import canvas
ImportError: No module named canvas
Traceback (most recent call last):
  File "scripts/node2.py", line 8, in <module>
    import canvas
ImportError: No module named canvas
Traceback (most recent call last):
  File "scripts/node2.py", line 8, in <module>
    import canvas
ImportError: No module named canvas
Traceback (most recent call last):
  File "scripts/node2.py", line 8, in <module>
    import canvas
ImportError: No module named canvas
Traceback (most recent call last):
  File "scripts/node2.py", line 8, in <module>
    import canvas
ImportError: No module named canvas
Traceback (most recent call last):
  File "scripts/node2.py", line 8, in <module>
    import canvas
ImportError: No module named canvas
Traceback (most recent call last):
  File "scripts/node2.py", line 8, in <module>
    import canvas
ImportError: No module named canvas
Traceback (most recent call last):
  File "scripts/node2.py", line 8, in <module>
    import canvas
ImportError: No module named canvas
Traceback (most recent call last):
  File "scripts/node2.py", line 8, in <module>
    import canvas
ImportError: No module named canvas
Traceback (most recent call last):
  File "scripts/node2.py", line 8, in <module>
    import canvas
ImportError: No module named canvas
Traceback (most recent call last):
  File "scripts/node2.py", line 8, in <module>
    import canvas
ImportError: No module named canvas
Traceback (most recent call last):
  File "scripts/node2.py", line 8, in <module>
    import canvas
ImportError: No module named canvas
Traceback (most recent call last):
  File "scripts/node2.py", line 46, in <module>
    main()
  File "scripts/node2.py", line 33, in main
    msg_id, msg_data = canvas.recv(receiver)
  File "/home/nebu/supervisor/scripts/canvas.py", line 35, in recv
    msg_id, data = can_message-split(' ', 1)
NameError: global name 'split' is not defined
  File "scripts/node2.py", line 36
    canvas.print_out("Node 2 recieved: %s %s%" % msg_id msg_data)
                                                               ^
SyntaxError: invalid syntax
  File "scripts/node2.py", line 36
    canvas.print_out("Node 2 recieved: %s %s%" % msg_id msg_data)
                                                               ^
SyntaxError: invalid syntax
  File "scripts/node2.py", line 36
    canvas.print_out("Node 2 recieved: %s %s%" % msg_id msg_data)
                                                               ^
SyntaxError: invalid syntax
  File "scripts/node2.py", line 36
    canvas.print_out("Node 2 recieved: %s %s%" % msg_id msg_data)
                                                               ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "scripts/node2.py", line 47, in <module>
    main()
  File "scripts/node2.py", line 36, in main
    canvas.print_out("Node 2 recieved: %s %s%" % (msg_id, msg_data))
ValueError: incomplete format
Traceback (most recent call last):
  File "scripts/node2.py", line 45, in <module>
    main()
  File "scripts/node2.py", line 39, in main
    canvas.print_out("Node 2 recieved: %s" % msg_id, msg_data)
TypeError: print_out() takes exactly 1 argument (2 given)
Traceback (most recent call last):
  File "scripts/node2.py", line 45, in <module>
    main()
  File "scripts/node2.py", line 39, in main
    canvas.print_out("Node 2 recieved: %s %s" % msg_id, msg_data)
TypeError: not enough arguments for format string
Traceback (most recent call last):
  File "scripts/node2.py", line 4, in <module>
    import canvas
  File "/home/nebu/supervisor/scripts/canvas.py", line 10, in <module>
    class message(a, b):
NameError: name 'a' is not defined
Traceback (most recent call last):
  File "scripts/node2.py", line 4, in <module>
    import canvas
  File "/home/nebu/supervisor/scripts/canvas.py", line 10, in <module>
    class message(a, b):
NameError: name 'a' is not defined
Traceback (most recent call last):
  File "scripts/node2.py", line 4, in <module>
    import canvas
  File "/home/nebu/supervisor/scripts/canvas.py", line 10, in <module>
    class message(a, b):
NameError: name 'a' is not defined
Traceback (most recent call last):
  File "scripts/node2.py", line 4, in <module>
    import canvas
  File "/home/nebu/supervisor/scripts/canvas.py", line 10, in <module>
    class message(a, b):
NameError: name 'a' is not defined
Traceback (most recent call last):
  File "scripts/node2.py", line 4, in <module>
    import canvas
  File "/home/nebu/supervisor/scripts/canvas.py", line 10, in <module>
    class message(a, b):
NameError: name 'a' is not defined
Traceback (most recent call last):
  File "scripts/node2.py", line 4, in <module>
    import canvas
  File "/home/nebu/supervisor/scripts/canvas.py", line 10, in <module>
    class message(a, b):
NameError: name 'a' is not defined
Traceback (most recent call last):
  File "scripts/node2.py", line 4, in <module>
    import canvas
  File "/home/nebu/supervisor/scripts/canvas.py", line 10, in <module>
    class message(a, b):
NameError: name 'a' is not defined
Traceback (most recent call last):
  File "scripts/node2.py", line 4, in <module>
    import canvas
  File "/home/nebu/supervisor/scripts/canvas.py", line 10, in <module>
    class message(a, b):
NameError: name 'a' is not defined
Traceback (most recent call last):
  File "scripts/node2.py", line 4, in <module>
    import canvas
  File "/home/nebu/supervisor/scripts/canvas.py", line 10, in <module>
    class message(a, b):
NameError: name 'a' is not defined
Traceback (most recent call last):
  File "scripts/node2.py", line 4, in <module>
    import canvas
  File "/home/nebu/supervisor/scripts/canvas.py", line 10, in <module>
    class message(a, b):
NameError: name 'a' is not defined
Traceback (most recent call last):
  File "scripts/node2.py", line 4, in <module>
    import canvas
  File "/home/nebu/supervisor/scripts/canvas.py", line 10, in <module>
    class message(a, b):
NameError: name 'a' is not defined
Traceback (most recent call last):
  File "scripts/node2.py", line 4, in <module>
    import canvas
  File "/home/nebu/supervisor/scripts/canvas.py", line 10, in <module>
    class message(a, b):
NameError: name 'a' is not defined
Traceback (most recent call last):
  File "scripts/node2.py", line 4, in <module>
    import canvas
  File "/home/nebu/supervisor/scripts/canvas.py", line 10, in <module>
    class message(a, b):
NameError: name 'a' is not defined
Traceback (most recent call last):
  File "scripts/node2.py", line 4, in <module>
    import canvas
  File "/home/nebu/supervisor/scripts/canvas.py", line 10, in <module>
    class message(a, b):
NameError: name 'a' is not defined
Traceback (most recent call last):
  File "scripts/node2.py", line 4, in <module>
    import canvas
  File "/home/nebu/supervisor/scripts/canvas.py", line 10, in <module>
    class message(a, b):
NameError: name 'a' is not defined
Traceback (most recent call last):
  File "scripts/node2.py", line 47, in <module>
    main()
  File "scripts/node2.py", line 18, in main
    message = canvas.message()
TypeError: __init__() takes exactly 3 arguments (1 given)
Traceback (most recent call last):
  File "scripts/node2.py", line 47, in <module>
    main()
  File "scripts/node2.py", line 18, in main
    message = canvas.message()
TypeError: __init__() takes exactly 3 arguments (1 given)
Traceback (most recent call last):
  File "scripts/node2.py", line 47, in <module>
    main()
  File "scripts/node2.py", line 18, in main
    message = canvas.message()
TypeError: __init__() takes exactly 3 arguments (1 given)
Traceback (most recent call last):
  File "scripts/node2.py", line 47, in <module>
    main()
  File "scripts/node2.py", line 18, in main
    message = canvas.message()
TypeError: __init__() takes exactly 3 arguments (1 given)
Traceback (most recent call last):
  File "scripts/node2.py", line 47, in <module>
    main()
  File "scripts/node2.py", line 18, in main
    message = canvas.message()
TypeError: __init__() takes exactly 3 arguments (1 given)
Traceback (most recent call last):
  File "scripts/node2.py", line 47, in <module>
    main()
  File "scripts/node2.py", line 18, in main
    message = canvas.message()
TypeError: __init__() takes exactly 3 arguments (1 given)
Traceback (most recent call last):
  File "scripts/node2.py", line 47, in <module>
    main()
  File "scripts/node2.py", line 18, in main
    message = canvas.message()
TypeError: __init__() takes exactly 3 arguments (1 given)
Traceback (most recent call last):
  File "scripts/node2.py", line 50, in <module>
    main()
  File "scripts/node2.py", line 32, in main
    canvas.send_msg(sender, message)	    	
  File "/home/nebu/supervisor/scripts/canvas.py", line 35, in send_msg
    socket.send("%s %s" % (msg[0], msg[1]))
AttributeError: message instance has no attribute '__getitem__'
Traceback (most recent call last):
  File "scripts/node2.py", line 50, in <module>
    main()
  File "scripts/node2.py", line 32, in main
    canvas.send_msg(sender, message)	    	
  File "/home/nebu/supervisor/scripts/canvas.py", line 35, in send_msg
    socket.send("%s %s" % (msg[0], msg[1]))
AttributeError: message instance has no attribute '__getitem__'
Traceback (most recent call last):
  File "scripts/node2.py", line 50, in <module>
    main()
  File "scripts/node2.py", line 32, in main
    canvas.send_msg(sender, message)	    	
  File "/home/nebu/supervisor/scripts/canvas.py", line 35, in send_msg
    socket.send("%s %s" % (msg[0], msg[1]))
AttributeError: message instance has no attribute '__getitem__'
Traceback (most recent call last):
  File "scripts/node2.py", line 50, in <module>
    main()
  File "scripts/node2.py", line 32, in main
    canvas.send_msg(sender, message)	    	
  File "/home/nebu/supervisor/scripts/canvas.py", line 35, in send_msg
    socket.send("%s %s" % (msg[0], msg[1]))
AttributeError: message instance has no attribute '__getitem__'
Traceback (most recent call last):
  File "scripts/node2.py", line 50, in <module>
    main()
  File "scripts/node2.py", line 32, in main
    canvas.send_msg(sender, message)	    	
  File "/home/nebu/supervisor/scripts/canvas.py", line 35, in send_msg
    socket.send("%s %s" % (msg[0], msg[1]))
AttributeError: message instance has no attribute '__getitem__'
Traceback (most recent call last):
  File "scripts/node2.py", line 56, in <module>
    main()
  File "scripts/node2.py", line 16, in main
    canvas.add_id(receiver, receive_message_ids)
AttributeError: 'module' object has no attribute 'add_id'
Traceback (most recent call last):
  File "scripts/node2.py", line 56, in <module>
    main()
  File "scripts/node2.py", line 16, in main
    canvas.add_id(receiver, receive_message_ids)
AttributeError: 'module' object has no attribute 'add_id'
Traceback (most recent call last):
  File "scripts/node2.py", line 56, in <module>
    main()
  File "scripts/node2.py", line 16, in main
    canvas.add_id(receiver, receive_message_ids)
AttributeError: 'module' object has no attribute 'add_id'
Traceback (most recent call last):
  File "scripts/node2.py", line 56, in <module>
    main()
  File "scripts/node2.py", line 16, in main
    canvas.add_id(receiver, receive_message_ids)
AttributeError: 'module' object has no attribute 'add_id'
Traceback (most recent call last):
  File "scripts/node2.py", line 56, in <module>
    main()
  File "scripts/node2.py", line 16, in main
    canvas.add_id(receiver, receive_message_ids)
AttributeError: 'module' object has no attribute 'add_id'
